// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminSession = `-- name: GetAdminSession :one
SELECT token_fingerprint, expires_at, last_activity
FROM admin_sessions
WHERE session_hash = $1
`

type GetAdminSessionRow struct {
	TokenFingerprint []byte
	ExpiresAt        pgtype.Timestamptz
	LastActivity     pgtype.Timestamptz
}

// Look up a session by its SHA-256 hash. Returns the row's fingerprint,
// expiry, and last-activity timestamp.
func (q *Queries) GetAdminSession(ctx context.Context, sessionHash []byte) (GetAdminSessionRow, error) {
	row := q.db.QueryRow(ctx, getAdminSession, sessionHash)
	var i GetAdminSessionRow
	err := row.Scan(&i.TokenFingerprint, &i.ExpiresAt, &i.LastActivity)
	return i, err
}

const insertAdminSession = `-- name: InsertAdminSession :exec
INSERT INTO admin_sessions (session_hash, token_fingerprint, expires_at, last_activity)
VALUES ($1, $2, $3, $4)
`

type InsertAdminSessionParams struct {
	SessionHash      []byte
	TokenFingerprint []byte
	ExpiresAt        pgtype.Timestamptz
	LastActivity     pgtype.Timestamptz
}

// Insert a new admin session row. Returns an error if a session with the
// same hash already exists (unique primary key).
func (q *Queries) InsertAdminSession(ctx context.Context, arg InsertAdminSessionParams) error {
	_, err := q.db.Exec(ctx, insertAdminSession,
		arg.SessionHash,
		arg.TokenFingerprint,
		arg.ExpiresAt,
		arg.LastActivity,
	)
	return err
}

const sweepExpiredAdminSessions = `-- name: SweepExpiredAdminSessions :execrows
DELETE FROM admin_sessions
WHERE expires_at < now()
`

// Delete session rows whose absolute expiry deadline has passed.
func (q *Queries) SweepExpiredAdminSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredAdminSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAdminSessionActivity = `-- name: UpdateAdminSessionActivity :execrows
UPDATE admin_sessions
SET last_activity = GREATEST(last_activity, $2)
WHERE session_hash = $1
`

type UpdateAdminSessionActivityParams struct {
	SessionHash  []byte
	LastActivity pgtype.Timestamptz
}

// Touch the last_activity timestamp for an existing session. Uses GREATEST
// so concurrent requests committing out of order never move the clock
// backwards and trigger a spurious idle-timeout. Returns rows affected
// (0 means the session was deleted between lookup and update).
func (q *Queries) UpdateAdminSessionActivity(ctx context.Context, arg UpdateAdminSessionActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAdminSessionActivity, arg.SessionHash, arg.LastActivity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
