// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_keys.sql

package db

import (
	"context"
)

const authKeyByID = `-- name: AuthKeyByID :one
SELECT id, key_value, user_id, created_at, last_seen_at FROM auth_keys WHERE id = $1
`

func (q *Queries) AuthKeyByID(ctx context.Context, id int64) (AuthKey, error) {
	row := q.db.QueryRow(ctx, authKeyByID, id)
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.KeyValue,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const authKeysByUser = `-- name: AuthKeysByUser :many
SELECT id, key_value, user_id, created_at, last_seen_at FROM auth_keys WHERE user_id = $1
`

func (q *Queries) AuthKeysByUser(ctx context.Context, userID *int64) ([]AuthKey, error) {
	rows, err := q.db.Query(ctx, authKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthKey
	for rows.Next() {
		var i AuthKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyValue,
			&i.UserID,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bindAuthKeyUser = `-- name: BindAuthKeyUser :execrows
UPDATE auth_keys SET user_id = $2 WHERE id = $1
`

type BindAuthKeyUserParams struct {
	ID     int64
	UserID *int64
}

func (q *Queries) BindAuthKeyUser(ctx context.Context, arg BindAuthKeyUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindAuthKeyUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAuthKey = `-- name: DeleteAuthKey :exec
DELETE FROM auth_keys WHERE id = $1
`

func (q *Queries) DeleteAuthKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAuthKey, id)
	return err
}

const saveAuthKey = `-- name: SaveAuthKey :exec
INSERT INTO auth_keys (id, key_value)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
  SET key_value = EXCLUDED.key_value,
      last_seen_at = now()
`

type SaveAuthKeyParams struct {
	ID       int64
	KeyValue []byte
}

func (q *Queries) SaveAuthKey(ctx context.Context, arg SaveAuthKeyParams) error {
	_, err := q.db.Exec(ctx, saveAuthKey, arg.ID, arg.KeyValue)
	return err
}
