// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockedUsers = `-- name: BlockedUsers :many
SELECT blocked_id, created_at, COUNT(*) OVER() AS total
FROM blocked_users
WHERE blocker_id = $1
ORDER BY created_at DESC, blocked_id DESC
LIMIT $3::int OFFSET $2::int
`

type BlockedUsersParams struct {
	BlockerID int64
	Off       int32
	Lim       int32
}

type BlockedUsersRow struct {
	BlockedID int64
	CreatedAt pgtype.Timestamptz
	Total     int64
}

func (q *Queries) BlockedUsers(ctx context.Context, arg BlockedUsersParams) ([]BlockedUsersRow, error) {
	rows, err := q.db.Query(ctx, blockedUsers, arg.BlockerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockedUsersRow
	for rows.Next() {
		var i BlockedUsersRow
		if err := rows.Scan(&i.BlockedID, &i.CreatedAt, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBlockedUsers = `-- name: CountBlockedUsers :one
SELECT COUNT(*) FROM blocked_users WHERE blocker_id = $1
`

func (q *Queries) CountBlockedUsers(ctx context.Context, blockerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBlockedUsers, blockerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBlockedUser = `-- name: DeleteBlockedUser :execrows
DELETE FROM blocked_users
WHERE blocker_id = $1 AND blocked_id = $2
`

type DeleteBlockedUserParams struct {
	BlockerID int64
	BlockedID int64
}

func (q *Queries) DeleteBlockedUser(ctx context.Context, arg DeleteBlockedUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlockedUser, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBlockedUser = `-- name: InsertBlockedUser :execrows
INSERT INTO blocked_users (blocker_id, blocked_id)
VALUES ($1, $2)
ON CONFLICT (blocker_id, blocked_id) DO NOTHING
`

type InsertBlockedUserParams struct {
	BlockerID int64
	BlockedID int64
}

func (q *Queries) InsertBlockedUser(ctx context.Context, arg InsertBlockedUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBlockedUser, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS(
    SELECT 1 FROM blocked_users
    WHERE blocker_id = $1 AND blocked_id = $2
)
`

type IsBlockedParams struct {
	BlockerID int64
	BlockedID int64
}

func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.BlockerID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
