// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channelmsgs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpChannelState = `-- name: BumpChannelState :one
UPDATE channel_state
SET pts = pts + 1, next_local_id = next_local_id + 1, date = now()
WHERE channel_id = $1
RETURNING pts, (next_local_id - 1)::bigint AS local_id
`

type BumpChannelStateRow struct {
	Pts     int64
	LocalID int64
}

// BumpChannelState allocates the next local_id and advances pts in one step. It
// returns the new pts and the local_id just consumed (pre-increment value).
func (q *Queries) BumpChannelState(ctx context.Context, channelID int64) (BumpChannelStateRow, error) {
	row := q.db.QueryRow(ctx, bumpChannelState, channelID)
	var i BumpChannelStateRow
	err := row.Scan(&i.Pts, &i.LocalID)
	return i, err
}

const channelEventsWindow = `-- name: ChannelEventsWindow :many
SELECT channel_id, pts, type, local_id FROM channel_events
WHERE channel_id = $1 AND pts > $2 AND pts <= $3
ORDER BY pts
LIMIT $4::int
`

type ChannelEventsWindowParams struct {
	ChannelID int64
	FromPts   int64
	ToPts     int64
	Lim       int32
}

// ChannelEventsWindow returns events in (from_pts, to_pts] ordered, capped by
// lim. The upper bound pins the read to a pts snapshot so the difference never
// advertises a pts past an event it omitted.
func (q *Queries) ChannelEventsWindow(ctx context.Context, arg ChannelEventsWindowParams) ([]ChannelEvent, error) {
	rows, err := q.db.Query(ctx, channelEventsWindow,
		arg.ChannelID,
		arg.FromPts,
		arg.ToPts,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelEvent
	for rows.Next() {
		var i ChannelEvent
		if err := rows.Scan(
			&i.ChannelID,
			&i.Pts,
			&i.Type,
			&i.LocalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelHistoryPage = `-- name: ChannelHistoryPage :many
SELECT channel_id, local_id, from_id, date, message, edit_date, deleted, random_id, file_id
FROM channel_messages
WHERE channel_id = $1 AND deleted = false
  AND ($2::bigint = 0 OR local_id < $2::bigint)
ORDER BY local_id DESC
LIMIT $3::int
`

type ChannelHistoryPageParams struct {
	ChannelID int64
	OffsetID  int64
	Lim       int32
}

type ChannelHistoryPageRow struct {
	ChannelID int64
	LocalID   int64
	FromID    int64
	Date      pgtype.Timestamptz
	Message   string
	EditDate  pgtype.Timestamptz
	Deleted   bool
	RandomID  int64
	FileID    *int64
}

func (q *Queries) ChannelHistoryPage(ctx context.Context, arg ChannelHistoryPageParams) ([]ChannelHistoryPageRow, error) {
	rows, err := q.db.Query(ctx, channelHistoryPage, arg.ChannelID, arg.OffsetID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelHistoryPageRow
	for rows.Next() {
		var i ChannelHistoryPageRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.LocalID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.FileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelMessageByLocal = `-- name: ChannelMessageByLocal :one
SELECT channel_id, local_id, from_id, date, message, edit_date, deleted, random_id, file_id
FROM channel_messages WHERE channel_id = $1 AND local_id = $2
`

type ChannelMessageByLocalParams struct {
	ChannelID int64
	LocalID   int64
}

type ChannelMessageByLocalRow struct {
	ChannelID int64
	LocalID   int64
	FromID    int64
	Date      pgtype.Timestamptz
	Message   string
	EditDate  pgtype.Timestamptz
	Deleted   bool
	RandomID  int64
	FileID    *int64
}

func (q *Queries) ChannelMessageByLocal(ctx context.Context, arg ChannelMessageByLocalParams) (ChannelMessageByLocalRow, error) {
	row := q.db.QueryRow(ctx, channelMessageByLocal, arg.ChannelID, arg.LocalID)
	var i ChannelMessageByLocalRow
	err := row.Scan(
		&i.ChannelID,
		&i.LocalID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.FileID,
	)
	return i, err
}

const channelMessageByRandomID = `-- name: ChannelMessageByRandomID :one
SELECT channel_id, local_id, from_id, date, message, edit_date, deleted, random_id, file_id
FROM channel_messages WHERE channel_id = $1 AND random_id = $2 AND random_id <> 0
`

type ChannelMessageByRandomIDParams struct {
	ChannelID int64
	RandomID  int64
}

type ChannelMessageByRandomIDRow struct {
	ChannelID int64
	LocalID   int64
	FromID    int64
	Date      pgtype.Timestamptz
	Message   string
	EditDate  pgtype.Timestamptz
	Deleted   bool
	RandomID  int64
	FileID    *int64
}

func (q *Queries) ChannelMessageByRandomID(ctx context.Context, arg ChannelMessageByRandomIDParams) (ChannelMessageByRandomIDRow, error) {
	row := q.db.QueryRow(ctx, channelMessageByRandomID, arg.ChannelID, arg.RandomID)
	var i ChannelMessageByRandomIDRow
	err := row.Scan(
		&i.ChannelID,
		&i.LocalID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.FileID,
	)
	return i, err
}

const channelMessagesByLocalIDs = `-- name: ChannelMessagesByLocalIDs :many
SELECT channel_id, local_id, from_id, date, message, edit_date, deleted, random_id, file_id
FROM channel_messages
WHERE channel_id = $1 AND local_id = ANY($2::bigint[])
`

type ChannelMessagesByLocalIDsParams struct {
	ChannelID int64
	LocalIds  []int64
}

type ChannelMessagesByLocalIDsRow struct {
	ChannelID int64
	LocalID   int64
	FromID    int64
	Date      pgtype.Timestamptz
	Message   string
	EditDate  pgtype.Timestamptz
	Deleted   bool
	RandomID  int64
	FileID    *int64
}

func (q *Queries) ChannelMessagesByLocalIDs(ctx context.Context, arg ChannelMessagesByLocalIDsParams) ([]ChannelMessagesByLocalIDsRow, error) {
	rows, err := q.db.Query(ctx, channelMessagesByLocalIDs, arg.ChannelID, arg.LocalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMessagesByLocalIDsRow
	for rows.Next() {
		var i ChannelMessagesByLocalIDsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.LocalID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.FileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureChannelState = `-- name: EnsureChannelState :exec
INSERT INTO channel_state (channel_id) VALUES ($1) ON CONFLICT (channel_id) DO NOTHING
`

func (q *Queries) EnsureChannelState(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, ensureChannelState, channelID)
	return err
}

const getChannelState = `-- name: GetChannelState :one
SELECT channel_id, pts, next_local_id, date FROM channel_state WHERE channel_id = $1
`

func (q *Queries) GetChannelState(ctx context.Context, channelID int64) (ChannelState, error) {
	row := q.db.QueryRow(ctx, getChannelState, channelID)
	var i ChannelState
	err := row.Scan(
		&i.ChannelID,
		&i.Pts,
		&i.NextLocalID,
		&i.Date,
	)
	return i, err
}

const insertChannelEvent = `-- name: InsertChannelEvent :exec
INSERT INTO channel_events (channel_id, pts, type, local_id) VALUES ($1, $2, $3, $4)
`

type InsertChannelEventParams struct {
	ChannelID int64
	Pts       int64
	Type      int16
	LocalID   int64
}

func (q *Queries) InsertChannelEvent(ctx context.Context, arg InsertChannelEventParams) error {
	_, err := q.db.Exec(ctx, insertChannelEvent,
		arg.ChannelID,
		arg.Pts,
		arg.Type,
		arg.LocalID,
	)
	return err
}

const insertChannelMessage = `-- name: InsertChannelMessage :exec
INSERT INTO channel_messages (channel_id, local_id, from_id, message, random_id, file_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertChannelMessageParams struct {
	ChannelID int64
	LocalID   int64
	FromID    int64
	Message   string
	RandomID  int64
	FileID    *int64
}

func (q *Queries) InsertChannelMessage(ctx context.Context, arg InsertChannelMessageParams) error {
	_, err := q.db.Exec(ctx, insertChannelMessage,
		arg.ChannelID,
		arg.LocalID,
		arg.FromID,
		arg.Message,
		arg.RandomID,
		arg.FileID,
	)
	return err
}

const lockChannelState = `-- name: LockChannelState :one
SELECT channel_id, pts, next_local_id, date FROM channel_state WHERE channel_id = $1 FOR UPDATE
`

// LockChannelState takes the channel_state row lock ahead of the dedup read, so
// two concurrent posts carrying the same random_id cannot both miss it. It is
// the same row the bump below locks, taken one statement earlier.
func (q *Queries) LockChannelState(ctx context.Context, channelID int64) (ChannelState, error) {
	row := q.db.QueryRow(ctx, lockChannelState, channelID)
	var i ChannelState
	err := row.Scan(
		&i.ChannelID,
		&i.Pts,
		&i.NextLocalID,
		&i.Date,
	)
	return i, err
}
