// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const channelByID = `-- name: ChannelByID :one
SELECT id, title, about, creator_id, megagroup, version, date FROM channels WHERE id = $1
`

func (q *Queries) ChannelByID(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, channelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
	)
	return i, err
}

const channelDialogsForUser = `-- name: ChannelDialogsForUser :many
SELECT
    c.id AS channel_id,
    c.title,
    c.about,
    c.creator_id,
    c.megagroup,
    c.version,
    c.date AS channel_date,
    cs.pts,
    cs.next_local_id,
    cs.date AS state_date,
    COALESCE(top.local_id, 0)  AS top_local_id,
    COALESCE(top.from_id, 0)   AS top_from_id,
    top.date                   AS top_date,
    COALESCE(top.message, '')  AS top_message,
    top.edit_date              AS top_edit_date,
    COALESCE(top.deleted, false) AS top_deleted,
    COALESCE(top.random_id, 0) AS top_random_id,
    top.file_id                AS top_file_id
FROM channels c
JOIN channel_participants p ON p.channel_id = c.id
JOIN channel_state cs ON cs.channel_id = c.id
LEFT JOIN LATERAL (
    SELECT cm.channel_id, cm.local_id, cm.from_id, cm.date, cm.message, cm.edit_date, cm.deleted, cm.random_id, cm.file_id
    FROM channel_messages cm
    WHERE cm.channel_id = c.id AND cm.deleted = false
    ORDER BY cm.local_id DESC
    LIMIT 1
) top ON true
WHERE p.user_id = $1
ORDER BY c.id
`

type ChannelDialogsForUserRow struct {
	ChannelID   int64
	Title       string
	About       string
	CreatorID   int64
	Megagroup   bool
	Version     int32
	ChannelDate pgtype.Timestamptz
	Pts         int64
	NextLocalID int64
	StateDate   pgtype.Timestamptz
	TopLocalID  int64
	TopFromID   int64
	TopDate     pgtype.Timestamptz
	TopMessage  string
	TopEditDate pgtype.Timestamptz
	TopDeleted  bool
	TopRandomID int64
	TopFileID   *int64
}

// ChannelDialogsForUser returns every channel the user belongs to alongside the
// channel's pts and the newest non-deleted post (the "top message" for the
// dialog list). Channels with no posts or whose newest post is deleted appear
// with top_local_id = 0 so the caller can skip them. LEFT JOIN is deliberate:
// the 100-channel cap applies to the candidate set (all memberships), not to
// the filtered set, so an empty channel still counts against the cap.
// COALESCE guards against NULL from the lateral join; local_id >= 1 so 0 is
// a safe sentinel for "no row".
func (q *Queries) ChannelDialogsForUser(ctx context.Context, userID int64) ([]ChannelDialogsForUserRow, error) {
	rows, err := q.db.Query(ctx, channelDialogsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelDialogsForUserRow
	for rows.Next() {
		var i ChannelDialogsForUserRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Title,
			&i.About,
			&i.CreatorID,
			&i.Megagroup,
			&i.Version,
			&i.ChannelDate,
			&i.Pts,
			&i.NextLocalID,
			&i.StateDate,
			&i.TopLocalID,
			&i.TopFromID,
			&i.TopDate,
			&i.TopMessage,
			&i.TopEditDate,
			&i.TopDeleted,
			&i.TopRandomID,
			&i.TopFileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelInviteByHash = `-- name: ChannelInviteByHash :one
SELECT hash, channel_id, creator_id, date FROM channel_invites WHERE hash = $1
`

// ChannelInviteByHash is the ONLY way into a channel. It is keyed on the hash
// alone and takes no channel id, so the dense channels.id space is not an
// admission input and cannot be walked. An unknown hash and an unusable one are
// one rejection upstream — see JoinChannelByInvite.
func (q *Queries) ChannelInviteByHash(ctx context.Context, hash string) (ChannelInvite, error) {
	row := q.db.QueryRow(ctx, channelInviteByHash, hash)
	var i ChannelInvite
	err := row.Scan(
		&i.Hash,
		&i.ChannelID,
		&i.CreatorID,
		&i.Date,
	)
	return i, err
}

const channelParticipantByUser = `-- name: ChannelParticipantByUser :one
SELECT channel_id, user_id, role, banned_until, join_pts, date FROM channel_participants WHERE channel_id = $1 AND user_id = $2
`

type ChannelParticipantByUserParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) ChannelParticipantByUser(ctx context.Context, arg ChannelParticipantByUserParams) (ChannelParticipant, error) {
	row := q.db.QueryRow(ctx, channelParticipantByUser, arg.ChannelID, arg.UserID)
	var i ChannelParticipant
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Role,
		&i.BannedUntil,
		&i.JoinPts,
		&i.Date,
	)
	return i, err
}

const channelParticipants = `-- name: ChannelParticipants :many
SELECT channel_id, user_id, role, banned_until, join_pts, date FROM channel_participants WHERE channel_id = $1 ORDER BY user_id
`

func (q *Queries) ChannelParticipants(ctx context.Context, channelID int64) ([]ChannelParticipant, error) {
	rows, err := q.db.Query(ctx, channelParticipants, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelParticipant
	for rows.Next() {
		var i ChannelParticipant
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Role,
			&i.BannedUntil,
			&i.JoinPts,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelStateForUpdate = `-- name: ChannelStateForUpdate :one
SELECT channel_id, pts, next_local_id, date FROM channel_state WHERE channel_id = $1 FOR UPDATE
`

// ChannelStateForUpdate takes the channel_state row lock that serialises
// admission to one channel: the pts a joiner records and the participant count
// the caps are decided on are both read under it. See the lock-order comment at
// the top of channels.go.
func (q *Queries) ChannelStateForUpdate(ctx context.Context, channelID int64) (ChannelState, error) {
	row := q.db.QueryRow(ctx, channelStateForUpdate, channelID)
	var i ChannelState
	err := row.Scan(
		&i.ChannelID,
		&i.Pts,
		&i.NextLocalID,
		&i.Date,
	)
	return i, err
}

const channelsForUser = `-- name: ChannelsForUser :many
SELECT c.id, c.title, c.about, c.creator_id, c.megagroup, c.version, c.date FROM channels c
JOIN channel_participants p ON p.channel_id = c.id
WHERE p.user_id = $1
ORDER BY c.id
`

func (q *Queries) ChannelsForUser(ctx context.Context, userID int64) ([]Channel, error) {
	rows, err := q.db.Query(ctx, channelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.About,
			&i.CreatorID,
			&i.Megagroup,
			&i.Version,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countChannelParticipants = `-- name: CountChannelParticipants :one
SELECT count(*) FROM channel_participants WHERE channel_id = $1
`

func (q *Queries) CountChannelParticipants(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelParticipants, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChannelsForUser = `-- name: CountChannelsForUser :one
SELECT count(*) FROM channel_participants WHERE user_id = $1
`

// CountChannelsForUser backs the per-account cap. It counts memberships, so a
// channel the account was removed from stops counting against it.
func (q *Queries) CountChannelsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChannelParticipant = `-- name: DeleteChannelParticipant :execrows
DELETE FROM channel_participants WHERE channel_id = $1 AND user_id = $2
`

type DeleteChannelParticipantParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) DeleteChannelParticipant(ctx context.Context, arg DeleteChannelParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelParticipant, arg.ChannelID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertChannel = `-- name: InsertChannel :one
INSERT INTO channels (title, about, creator_id, megagroup) VALUES ($1, $2, $3, $4)
RETURNING id, title, about, creator_id, megagroup, version, date
`

type InsertChannelParams struct {
	Title     string
	About     string
	CreatorID int64
	Megagroup bool
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, insertChannel,
		arg.Title,
		arg.About,
		arg.CreatorID,
		arg.Megagroup,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
	)
	return i, err
}

const insertChannelInvite = `-- name: InsertChannelInvite :exec
INSERT INTO channel_invites (hash, channel_id, creator_id) VALUES ($1, $2, $3)
`

type InsertChannelInviteParams struct {
	Hash      string
	ChannelID int64
	CreatorID int64
}

func (q *Queries) InsertChannelInvite(ctx context.Context, arg InsertChannelInviteParams) error {
	_, err := q.db.Exec(ctx, insertChannelInvite, arg.Hash, arg.ChannelID, arg.CreatorID)
	return err
}

const insertChannelParticipant = `-- name: InsertChannelParticipant :exec
INSERT INTO channel_participants (channel_id, user_id, role, join_pts) VALUES ($1, $2, $3, $4)
`

type InsertChannelParticipantParams struct {
	ChannelID int64
	UserID    int64
	Role      int16
	JoinPts   int64
}

func (q *Queries) InsertChannelParticipant(ctx context.Context, arg InsertChannelParticipantParams) error {
	_, err := q.db.Exec(ctx, insertChannelParticipant,
		arg.ChannelID,
		arg.UserID,
		arg.Role,
		arg.JoinPts,
	)
	return err
}

const insertChannelParticipantIfAbsent = `-- name: InsertChannelParticipantIfAbsent :execrows
INSERT INTO channel_participants (channel_id, user_id, role, join_pts) VALUES ($1, $2, $3, $4)
ON CONFLICT (channel_id, user_id) DO NOTHING
`

type InsertChannelParticipantIfAbsentParams struct {
	ChannelID int64
	UserID    int64
	Role      int16
	JoinPts   int64
}

// InsertChannelParticipantIfAbsent reports 0 rows when the user already holds a
// row, which is what makes a repeated join a no-op instead of an error — and in
// particular never lowers an existing join_pts or clears an existing ban.
func (q *Queries) InsertChannelParticipantIfAbsent(ctx context.Context, arg InsertChannelParticipantIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertChannelParticipantIfAbsent,
		arg.ChannelID,
		arg.UserID,
		arg.Role,
		arg.JoinPts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertChannelState = `-- name: InsertChannelState :exec
INSERT INTO channel_state (channel_id) VALUES ($1)
`

func (q *Queries) InsertChannelState(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, insertChannelState, channelID)
	return err
}

const isChannelMember = `-- name: IsChannelMember :one
SELECT EXISTS(SELECT 1 FROM channel_participants WHERE channel_id = $1 AND user_id = $2)
`

type IsChannelMemberParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) IsChannelMember(ctx context.Context, arg IsChannelMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelMember, arg.ChannelID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockChannel = `-- name: LockChannel :one
SELECT id, title, about, creator_id, megagroup, version, date FROM channels WHERE id = $1 FOR UPDATE
`

// LockChannel takes the channels row lock that serialises the rights mutations:
// the caller's and the target's participant rows are read under it and the write
// lands under it, so a demotion cannot interleave with the promotion it revokes.
// See the lock-order comment at the top of channels.go.
func (q *Queries) LockChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, lockChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
	)
	return i, err
}

const updateChannelParticipantBan = `-- name: UpdateChannelParticipantBan :execrows
UPDATE channel_participants SET banned_until = $3 WHERE channel_id = $1 AND user_id = $2
`

type UpdateChannelParticipantBanParams struct {
	ChannelID   int64
	UserID      int64
	BannedUntil pgtype.Timestamptz
}

// banned_until takes SQL NULL to unban and 'infinity' for a permanent ban, so
// the parameter is a pgtype.Timestamptz — the same type the column decodes into.
func (q *Queries) UpdateChannelParticipantBan(ctx context.Context, arg UpdateChannelParticipantBanParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelParticipantBan, arg.ChannelID, arg.UserID, arg.BannedUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelParticipantRole = `-- name: UpdateChannelParticipantRole :execrows
UPDATE channel_participants SET role = $3 WHERE channel_id = $1 AND user_id = $2
`

type UpdateChannelParticipantRoleParams struct {
	ChannelID int64
	UserID    int64
	Role      int16
}

// UpdateChannelParticipantRole and UpdateChannelParticipantBan only ever update:
// neither may create a participant row, so 0 rows affected means the target is
// not a member and the caller rejects.
func (q *Queries) UpdateChannelParticipantRole(ctx context.Context, arg UpdateChannelParticipantRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelParticipantRole, arg.ChannelID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
