// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_post_summaries.sql

package db

import (
	"context"
)

const advanceChannelReadMarker = `-- name: AdvanceChannelReadMarker :exec
INSERT INTO channel_read_state (channel_id, user_id, read_max_id)
SELECT participant.channel_id, participant.user_id, $1::bigint
FROM channel_participants AS participant
WHERE participant.channel_id = $2::bigint
  AND participant.user_id = $3::bigint
  AND (participant.banned_until IS NULL OR participant.banned_until <= now())
ON CONFLICT (channel_id, user_id)
DO UPDATE SET read_max_id = GREATEST(channel_read_state.read_max_id, EXCLUDED.read_max_id)
WHERE EXCLUDED.read_max_id > channel_read_state.read_max_id
`

type AdvanceChannelReadMarkerParams struct {
	ReadMaxID int64
	ChannelID int64
	UserID    int64
}

// Call only after taking channels and channel_state locks in that order.
func (q *Queries) AdvanceChannelReadMarker(ctx context.Context, arg AdvanceChannelReadMarkerParams) error {
	_, err := q.db.Exec(ctx, advanceChannelReadMarker, arg.ReadMaxID, arg.ChannelID, arg.UserID)
	return err
}

const channelPostSummaryReadinessByChannel = `-- name: ChannelPostSummaryReadinessByChannel :one
SELECT version, ready
FROM channel_post_summary_state
WHERE channel_id = $1
`

type ChannelPostSummaryReadinessByChannelRow struct {
	Version int16
	Ready   bool
}

func (q *Queries) ChannelPostSummaryReadinessByChannel(ctx context.Context, channelID int64) (ChannelPostSummaryReadinessByChannelRow, error) {
	row := q.db.QueryRow(ctx, channelPostSummaryReadinessByChannel, channelID)
	var i ChannelPostSummaryReadinessByChannelRow
	err := row.Scan(&i.Version, &i.Ready)
	return i, err
}

const channelPostSummarySchemaInstalled = `-- name: ChannelPostSummarySchemaInstalled :one
SELECT to_regclass('public.channel_read_state') IS NOT NULL
   AND to_regclass('public.channel_post_summary_state') IS NOT NULL
   AND to_regclass('public.channel_post_summaries') IS NOT NULL
`

func (q *Queries) ChannelPostSummarySchemaInstalled(ctx context.Context) (*bool, error) {
	row := q.db.QueryRow(ctx, channelPostSummarySchemaInstalled)
	var column_1 *bool
	err := row.Scan(&column_1)
	return column_1, err
}

const channelPostSummaryUnavailableChannels = `-- name: ChannelPostSummaryUnavailableChannels :one
SELECT count(*)::bigint
FROM channels AS channel
LEFT JOIN channel_post_summary_state AS summary_state
  ON summary_state.channel_id = channel.id
WHERE summary_state.channel_id IS NULL
   OR summary_state.version <> 1
   OR summary_state.ready = false
`

func (q *Queries) ChannelPostSummaryUnavailableChannels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, channelPostSummaryUnavailableChannels)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const channelPostUnreadSuffixCounts = `-- name: ChannelPostUnreadSuffixCounts :one
WITH member AS MATERIALIZED (
    SELECT participant.user_id
    FROM channel_participants AS participant
    WHERE participant.channel_id = $1::bigint
      AND participant.user_id = $2::bigint
      AND (participant.banned_until IS NULL OR participant.banned_until <= now())
), summary_state AS MATERIALIZED (
    SELECT state.version, state.ready
    FROM channel_post_summary_state AS state
    WHERE state.channel_id = $1::bigint
), suffix_keys AS MATERIALIZED (
    SELECT 0::smallint AS depth, 0::bigint AS prefix
    WHERE $3::bigint = 0
    UNION ALL
    SELECT bits.depth::smallint AS depth,
           ((($3::bigint >> (64 - bits.depth)) << 1) | 1)::bigint AS prefix
    FROM generate_series(1, 63) AS bits(depth)
    WHERE $3::bigint > 0
      AND (($3::bigint >> (63 - bits.depth)) & 1) = 0
)
SELECT EXISTS (SELECT 1 FROM member) AS entitled,
       EXISTS (SELECT 1 FROM summary_state) AS status_exists,
       COALESCE((SELECT version FROM summary_state), 0)::smallint AS version,
       COALESCE((SELECT ready FROM summary_state), false)::boolean AS ready,
       COALESCE((
           SELECT sum((
               SELECT summary.live_count
               FROM channel_post_summaries AS summary
               WHERE summary.channel_id = $1::bigint
                 AND summary.scope_kind = 0
                 AND summary.author_id = 0
                 AND summary.depth = suffix_key.depth
                 AND summary.prefix = suffix_key.prefix
           ))::bigint
           FROM suffix_keys AS suffix_key
           WHERE EXISTS (SELECT 1 FROM member)
             AND EXISTS (SELECT 1 FROM summary_state WHERE version = 1 AND ready)
       ), 0)::bigint AS total_live,
       COALESCE((
           SELECT sum((
               SELECT summary.live_count
               FROM channel_post_summaries AS summary
               WHERE summary.channel_id = $1::bigint
                 AND summary.scope_kind = 1
                 AND summary.author_id = member.user_id
                 AND summary.depth = suffix_key.depth
                 AND summary.prefix = suffix_key.prefix
           ))::bigint
           FROM member
           CROSS JOIN suffix_keys AS suffix_key
           WHERE EXISTS (SELECT 1 FROM summary_state WHERE version = 1 AND ready)
       ), 0)::bigint AS author_live
`

type ChannelPostUnreadSuffixCountsParams struct {
	ChannelID int64
	ViewerID  int64
	Marker    int64
}

type ChannelPostUnreadSuffixCountsRow struct {
	Entitled     bool
	StatusExists bool
	Version      int16
	Ready        bool
	TotalLive    int64
	AuthorLive   int64
}

// Membership and readiness share this statement snapshot with the two exact
// suffix sums. Author scope comes only from the joined participant row.
// Each suffix has at most 63 keys, so the two correlated PK lookups are bounded
// at 126 equality probes and do not visit channel_messages.
func (q *Queries) ChannelPostUnreadSuffixCounts(ctx context.Context, arg ChannelPostUnreadSuffixCountsParams) (ChannelPostUnreadSuffixCountsRow, error) {
	row := q.db.QueryRow(ctx, channelPostUnreadSuffixCounts, arg.ChannelID, arg.ViewerID, arg.Marker)
	var i ChannelPostUnreadSuffixCountsRow
	err := row.Scan(
		&i.Entitled,
		&i.StatusExists,
		&i.Version,
		&i.Ready,
		&i.TotalLive,
		&i.AuthorLive,
	)
	return i, err
}

const channelReadMarkerForMember = `-- name: ChannelReadMarkerForMember :one
SELECT COALESCE(read_state.read_max_id, 0)::bigint AS read_max_id
FROM channel_participants AS participant
LEFT JOIN channel_read_state AS read_state
  ON read_state.channel_id = participant.channel_id
 AND read_state.user_id = participant.user_id
WHERE participant.channel_id = $1::bigint
  AND participant.user_id = $2::bigint
  AND (participant.banned_until IS NULL OR participant.banned_until <= now())
`

type ChannelReadMarkerForMemberParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) ChannelReadMarkerForMember(ctx context.Context, arg ChannelReadMarkerForMemberParams) (int64, error) {
	row := q.db.QueryRow(ctx, channelReadMarkerForMember, arg.ChannelID, arg.UserID)
	var read_max_id int64
	err := row.Scan(&read_max_id)
	return read_max_id, err
}

const initializeChannelPostSummaries = `-- name: InitializeChannelPostSummaries :exec
SELECT initialize_channel_post_summaries($1)
`

func (q *Queries) InitializeChannelPostSummaries(ctx context.Context, pChannelID int64) error {
	_, err := q.db.Exec(ctx, initializeChannelPostSummaries, pChannelID)
	return err
}

const lockChannelStateForPostSummaryInitialization = `-- name: LockChannelStateForPostSummaryInitialization :one
SELECT channel_id
FROM channel_state
WHERE channel_id = $1
FOR UPDATE
`

func (q *Queries) LockChannelStateForPostSummaryInitialization(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockChannelStateForPostSummaryInitialization, channelID)
	var channel_id int64
	err := row.Scan(&channel_id)
	return channel_id, err
}

const markChannelPostSummariesNotReady = `-- name: MarkChannelPostSummariesNotReady :exec
INSERT INTO channel_post_summary_state (channel_id, version, ready)
VALUES ($1, 1, false)
ON CONFLICT (channel_id)
DO UPDATE SET version = 1, ready = false
`

// Call only after taking channel_state FOR UPDATE. Readiness becomes false only
// in the explicit maintenance initializer, never on source mutation paths.
func (q *Queries) MarkChannelPostSummariesNotReady(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, markChannelPostSummariesNotReady, channelID)
	return err
}
