// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_username_changes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChannelUsernameChanges = `-- name: CountChannelUsernameChanges :one
SELECT COUNT(*)
FROM channel_username_changes
WHERE channel_id = $1
  AND changed_at >= $2
`

type CountChannelUsernameChangesParams struct {
	ChannelID int64
	ChangedAt pgtype.Timestamptz
}

// Count changes by channel_id since the cutoff.
func (q *Queries) CountChannelUsernameChanges(ctx context.Context, arg CountChannelUsernameChangesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelUsernameChanges, arg.ChannelID, arg.ChangedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredChannelUsernameChanges = `-- name: DeleteExpiredChannelUsernameChanges :exec
DELETE FROM channel_username_changes
WHERE channel_id = $1
  AND changed_at < $2
`

type DeleteExpiredChannelUsernameChangesParams struct {
	ChannelID int64
	ChangedAt pgtype.Timestamptz
}

// Remove changes older than the window for a specific channel.
func (q *Queries) DeleteExpiredChannelUsernameChanges(ctx context.Context, arg DeleteExpiredChannelUsernameChangesParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredChannelUsernameChanges, arg.ChannelID, arg.ChangedAt)
	return err
}

const insertChannelUsernameChange = `-- name: InsertChannelUsernameChange :exec
INSERT INTO channel_username_changes (channel_id, changed_at)
VALUES ($1, now())
`

// Record a channel username change.
func (q *Queries) InsertChannelUsernameChange(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, insertChannelUsernameChange, channelID)
	return err
}
