// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package db

import (
	"context"
)

const chatByID = `-- name: ChatByID :one
SELECT id, title, creator_id, version, date FROM chats WHERE id = $1
`

func (q *Queries) ChatByID(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, chatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
	)
	return i, err
}

const chatParticipants = `-- name: ChatParticipants :many
SELECT chat_id, user_id, inviter_id, date FROM chat_participants WHERE chat_id = $1 ORDER BY user_id
`

// ChatParticipants is ascending by user_id: the fan-out takes its advisory locks
// in that order, so a stable ascending member list is what keeps it deadlock-free.
func (q *Queries) ChatParticipants(ctx context.Context, chatID int64) ([]ChatParticipant, error) {
	rows, err := q.db.Query(ctx, chatParticipants, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatParticipant
	for rows.Next() {
		var i ChatParticipant
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.InviterID,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatsForUser = `-- name: ChatsForUser :many
SELECT c.id, c.title, c.creator_id, c.version, c.date FROM chats c
JOIN chat_participants p ON p.chat_id = c.id
WHERE p.user_id = $1
ORDER BY c.id
`

func (q *Queries) ChatsForUser(ctx context.Context, userID int64) ([]Chat, error) {
	rows, err := q.db.Query(ctx, chatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatorID,
			&i.Version,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChat = `-- name: InsertChat :one
INSERT INTO chats (title, creator_id) VALUES ($1, $2)
RETURNING id, title, creator_id, version, date
`

type InsertChatParams struct {
	Title     string
	CreatorID int64
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, insertChat, arg.Title, arg.CreatorID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
	)
	return i, err
}

const insertChatParticipant = `-- name: InsertChatParticipant :exec
INSERT INTO chat_participants (chat_id, user_id, inviter_id) VALUES ($1, $2, $3)
`

type InsertChatParticipantParams struct {
	ChatID    int64
	UserID    int64
	InviterID int64
}

func (q *Queries) InsertChatParticipant(ctx context.Context, arg InsertChatParticipantParams) error {
	_, err := q.db.Exec(ctx, insertChatParticipant, arg.ChatID, arg.UserID, arg.InviterID)
	return err
}

const isChatMember = `-- name: IsChatMember :one
SELECT EXISTS(SELECT 1 FROM chat_participants WHERE chat_id = $1 AND user_id = $2)
`

type IsChatMemberParams struct {
	ChatID int64
	UserID int64
}

func (q *Queries) IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatMember, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
