// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package db

import (
	"context"
)

const bumpChatVersion = `-- name: BumpChatVersion :one
UPDATE chats SET version = version + 1 WHERE id = $1 RETURNING id, title, creator_id, version, date, pinned_message_id
`

func (q *Queries) BumpChatVersion(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, bumpChatVersion, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
	)
	return i, err
}

const chatByID = `-- name: ChatByID :one
SELECT id, title, creator_id, version, date, pinned_message_id FROM chats WHERE id = $1
`

func (q *Queries) ChatByID(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, chatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
	)
	return i, err
}

const chatByIDForUpdate = `-- name: ChatByIDForUpdate :one
SELECT id, title, creator_id, version, date, pinned_message_id FROM chats WHERE id = $1 FOR UPDATE
`

// ChatByIDForUpdate takes the chats row lock that serialises everything touching
// one chat's member set: the fan-out reads the member set under it, and the
// membership mutations take it before changing that set. See the lock-order
// comment at the top of chats.go.
func (q *Queries) ChatByIDForUpdate(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, chatByIDForUpdate, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
	)
	return i, err
}

const chatParticipants = `-- name: ChatParticipants :many
SELECT chat_id, user_id, inviter_id, date FROM chat_participants WHERE chat_id = $1 ORDER BY user_id
`

// ChatParticipants is ascending by user_id: the fan-out takes its advisory locks
// in that order, so a stable ascending member list is what keeps it deadlock-free.
func (q *Queries) ChatParticipants(ctx context.Context, chatID int64) ([]ChatParticipant, error) {
	rows, err := q.db.Query(ctx, chatParticipants, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatParticipant
	for rows.Next() {
		var i ChatParticipant
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.InviterID,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatParticipantsOfChats = `-- name: ChatParticipantsOfChats :many
SELECT chat_id, user_id, inviter_id, date FROM chat_participants
WHERE chat_id = ANY($1::bigint[])
`

func (q *Queries) ChatParticipantsOfChats(ctx context.Context, chatIds []int64) ([]ChatParticipant, error) {
	rows, err := q.db.Query(ctx, chatParticipantsOfChats, chatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatParticipant
	for rows.Next() {
		var i ChatParticipant
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.InviterID,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatsForUser = `-- name: ChatsForUser :many
SELECT c.id, c.title, c.creator_id, c.version, c.date, c.pinned_message_id FROM chats c
JOIN chat_participants p ON p.chat_id = c.id
WHERE p.user_id = $1
ORDER BY c.id
`

func (q *Queries) ChatsForUser(ctx context.Context, userID int64) ([]Chat, error) {
	rows, err := q.db.Query(ctx, chatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatorID,
			&i.Version,
			&i.Date,
			&i.PinnedMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChatParticipant = `-- name: DeleteChatParticipant :execrows
DELETE FROM chat_participants WHERE chat_id = $1 AND user_id = $2
`

type DeleteChatParticipantParams struct {
	ChatID int64
	UserID int64
}

// DeleteChatParticipant is called from exactly one place: removeParticipant in
// chats.go, which also takes the removed user's advisory lock. See its comment.
func (q *Queries) DeleteChatParticipant(ctx context.Context, arg DeleteChatParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatParticipant, arg.ChatID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatPinnedMessage = `-- name: GetChatPinnedMessage :one
SELECT pinned_message_id FROM chats WHERE id = $1
`

// GetChatPinnedMessage reads the current pinned message id for a chat.
func (q *Queries) GetChatPinnedMessage(ctx context.Context, id int64) (*int32, error) {
	row := q.db.QueryRow(ctx, getChatPinnedMessage, id)
	var pinned_message_id *int32
	err := row.Scan(&pinned_message_id)
	return pinned_message_id, err
}

const insertChat = `-- name: InsertChat :one
INSERT INTO chats (title, creator_id) VALUES ($1, $2)
RETURNING id, title, creator_id, version, date, pinned_message_id
`

type InsertChatParams struct {
	Title     string
	CreatorID int64
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, insertChat, arg.Title, arg.CreatorID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
	)
	return i, err
}

const insertChatParticipant = `-- name: InsertChatParticipant :exec
INSERT INTO chat_participants (chat_id, user_id, inviter_id) VALUES ($1, $2, $3)
`

type InsertChatParticipantParams struct {
	ChatID    int64
	UserID    int64
	InviterID int64
}

func (q *Queries) InsertChatParticipant(ctx context.Context, arg InsertChatParticipantParams) error {
	_, err := q.db.Exec(ctx, insertChatParticipant, arg.ChatID, arg.UserID, arg.InviterID)
	return err
}

const insertChatParticipantIfAbsent = `-- name: InsertChatParticipantIfAbsent :execrows
INSERT INTO chat_participants (chat_id, user_id, inviter_id) VALUES ($1, $2, $3)
ON CONFLICT (chat_id, user_id) DO NOTHING
`

type InsertChatParticipantIfAbsentParams struct {
	ChatID    int64
	UserID    int64
	InviterID int64
}

// InsertChatParticipantIfAbsent reports 0 rows when the user is already a member,
// which is what makes a repeated add a no-op instead of an error.
func (q *Queries) InsertChatParticipantIfAbsent(ctx context.Context, arg InsertChatParticipantIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertChatParticipantIfAbsent, arg.ChatID, arg.UserID, arg.InviterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isChatMember = `-- name: IsChatMember :one
SELECT EXISTS(SELECT 1 FROM chat_participants WHERE chat_id = $1 AND user_id = $2)
`

type IsChatMemberParams struct {
	ChatID int64
	UserID int64
}

func (q *Queries) IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatMember, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setChatPinnedMessage = `-- name: SetChatPinnedMessage :one
UPDATE chats SET pinned_message_id = $2, version = version + 1 WHERE id = $1 RETURNING id, title, creator_id, version, date, pinned_message_id
`

type SetChatPinnedMessageParams struct {
	ID              int64
	PinnedMessageID *int32
}

// SetChatPinnedMessage sets or clears the pinned message id on a chat.
// The pinned_message_id is the local_id of the pinned message (identical across
// members for a given fanout). NULL clears the pin.
func (q *Queries) SetChatPinnedMessage(ctx context.Context, arg SetChatPinnedMessageParams) (Chat, error) {
	row := q.db.QueryRow(ctx, setChatPinnedMessage, arg.ID, arg.PinnedMessageID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
	)
	return i, err
}

const setChatTitle = `-- name: SetChatTitle :one
UPDATE chats SET title = $2, version = version + 1 WHERE id = $1 RETURNING id, title, creator_id, version, date, pinned_message_id
`

type SetChatTitleParams struct {
	ID    int64
	Title string
}

func (q *Queries) SetChatTitle(ctx context.Context, arg SetChatTitleParams) (Chat, error) {
	row := q.db.QueryRow(ctx, setChatTitle, arg.ID, arg.Title)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
	)
	return i, err
}
