// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCode = `-- name: GetCode :one
SELECT phone, code_hash, code, expires_at FROM phone_codes WHERE phone = $1
`

func (q *Queries) GetCode(ctx context.Context, phone string) (PhoneCode, error) {
	row := q.db.QueryRow(ctx, getCode, phone)
	var i PhoneCode
	err := row.Scan(
		&i.Phone,
		&i.CodeHash,
		&i.Code,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertCode = `-- name: UpsertCode :exec
INSERT INTO phone_codes (phone, code_hash, code, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (phone) DO UPDATE
  SET code_hash = EXCLUDED.code_hash,
      code = EXCLUDED.code,
      expires_at = EXCLUDED.expires_at
`

type UpsertCodeParams struct {
	Phone     string
	CodeHash  string
	Code      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpsertCode(ctx context.Context, arg UpsertCodeParams) error {
	_, err := q.db.Exec(ctx, upsertCode,
		arg.Phone,
		arg.CodeHash,
		arg.Code,
		arg.ExpiresAt,
	)
	return err
}
