// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeCode = `-- name: ConsumeCode :execrows
UPDATE phone_codes SET consumed_at = now()
WHERE phone = $1
  AND code_hash = $2
  AND code = $3
  AND consumed_at IS NULL
  AND expires_at >= now()
  AND attempts < $4
`

type ConsumeCodeParams struct {
	Phone    string
	CodeHash string
	Code     string
	Attempts int32
}

// Compare-and-swap: consume only the exact issued code, and only while it is
// still verifiable. The terminal-state guards live in the WHERE so a code that
// lost a race to a concurrent resend/consume/expiry affects zero rows.
func (q *Queries) ConsumeCode(ctx context.Context, arg ConsumeCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeCode,
		arg.Phone,
		arg.CodeHash,
		arg.Code,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredCodes = `-- name: DeleteExpiredCodes :execrows
DELETE FROM phone_codes WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCode = `-- name: GetCode :one
SELECT phone, code_hash, code, expires_at, attempts, consumed_at, created_at FROM phone_codes WHERE phone = $1
`

func (q *Queries) GetCode(ctx context.Context, phone string) (PhoneCode, error) {
	row := q.db.QueryRow(ctx, getCode, phone)
	var i PhoneCode
	err := row.Scan(
		&i.Phone,
		&i.CodeHash,
		&i.Code,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementCodeAttempts = `-- name: IncrementCodeAttempts :exec
UPDATE phone_codes SET attempts = attempts + 1
WHERE phone = $1 AND code_hash = $2
`

type IncrementCodeAttemptsParams struct {
	Phone    string
	CodeHash string
}

// Scoped to the exact issued code by its hash so a concurrent resend (new hash)
// is never charged for a failed attempt against the old code.
func (q *Queries) IncrementCodeAttempts(ctx context.Context, arg IncrementCodeAttemptsParams) error {
	_, err := q.db.Exec(ctx, incrementCodeAttempts, arg.Phone, arg.CodeHash)
	return err
}

const upsertCode = `-- name: UpsertCode :exec
INSERT INTO phone_codes (phone, code_hash, code, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (phone) DO UPDATE
  SET code_hash   = EXCLUDED.code_hash,
      code        = EXCLUDED.code,
      expires_at  = EXCLUDED.expires_at,
      attempts    = 0,
      consumed_at = NULL,
      created_at  = now()
`

type UpsertCodeParams struct {
	Phone     string
	CodeHash  string
	Code      string
	ExpiresAt pgtype.Timestamptz
}

// Issues a fresh code, resetting the hardening state (attempts, consumed_at,
// created_at) so a re-issue starts a clean single-use window.
func (q *Queries) UpsertCode(ctx context.Context, arg UpsertCodeParams) error {
	_, err := q.db.Exec(ctx, upsertCode,
		arg.Phone,
		arg.CodeHash,
		arg.Code,
		arg.ExpiresAt,
	)
	return err
}
