// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"
)

const contactExists = `-- name: ContactExists :one
SELECT EXISTS (
    SELECT 1 FROM user_contacts
    WHERE owner_id = $1 AND contact_id = $2
)
`

type ContactExistsParams struct {
	OwnerID   int64
	ContactID int64
}

func (q *Queries) ContactExists(ctx context.Context, arg ContactExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, contactExists, arg.OwnerID, arg.ContactID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countContacts = `-- name: CountContacts :one
SELECT COUNT(*) FROM user_contacts WHERE owner_id = $1
`

func (q *Queries) CountContacts(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countContacts, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM user_contacts
WHERE owner_id = $1 AND contact_id = $2
`

type DeleteContactParams struct {
	OwnerID   int64
	ContactID int64
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContact, arg.OwnerID, arg.ContactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteContacts = `-- name: DeleteContacts :execrows
DELETE FROM user_contacts
WHERE owner_id = $1
  AND contact_id = ANY($2::bigint[])
`

type DeleteContactsParams struct {
	OwnerID    int64
	ContactIds []int64
}

func (q *Queries) DeleteContacts(ctx context.Context, arg DeleteContactsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContacts, arg.OwnerID, arg.ContactIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertContact = `-- name: InsertContact :execrows
INSERT INTO user_contacts (owner_id, contact_id)
VALUES ($1, $2)
ON CONFLICT (owner_id, contact_id) DO NOTHING
`

type InsertContactParams struct {
	OwnerID   int64
	ContactID int64
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertContact, arg.OwnerID, arg.ContactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listContacts = `-- name: ListContacts :many
SELECT uc.contact_id,
       EXISTS (
           SELECT 1 FROM user_contacts reverse
           WHERE reverse.owner_id = uc.contact_id
             AND reverse.contact_id = uc.owner_id
       ) AS mutual,
       COUNT(*) OVER () AS total
FROM user_contacts uc
WHERE uc.owner_id = $1
ORDER BY uc.contact_id
`

type ListContactsRow struct {
	ContactID int64
	Mutual    bool
	Total     int64
}

func (q *Queries) ListContacts(ctx context.Context, ownerID int64) ([]ListContactsRow, error) {
	rows, err := q.db.Query(ctx, listContacts, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsRow
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(&i.ContactID, &i.Mutual, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
