// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dialog_filters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitDialogFilterMutation = `-- name: CommitDialogFilterMutation :exec
UPDATE user_dialog_filter_state
SET order_ids = $2, changed_at = clock_timestamp()
WHERE owner_id = $1
`

type CommitDialogFilterMutationParams struct {
	OwnerID  int64
	OrderIds []int16
}

func (q *Queries) CommitDialogFilterMutation(ctx context.Context, arg CommitDialogFilterMutationParams) error {
	_, err := q.db.Exec(ctx, commitDialogFilterMutation, arg.OwnerID, arg.OrderIds)
	return err
}

const commitUnreadDialogFilterSeed = `-- name: CommitUnreadDialogFilterSeed :exec
UPDATE user_dialog_filter_state
SET defaults_seeded = true, order_ids = $2, changed_at = clock_timestamp()
WHERE owner_id = $1
`

type CommitUnreadDialogFilterSeedParams struct {
	OwnerID  int64
	OrderIds []int16
}

func (q *Queries) CommitUnreadDialogFilterSeed(ctx context.Context, arg CommitUnreadDialogFilterSeedParams) error {
	_, err := q.db.Exec(ctx, commitUnreadDialogFilterSeed, arg.OwnerID, arg.OrderIds)
	return err
}

const deleteDialogFilter = `-- name: DeleteDialogFilter :execrows
DELETE FROM user_dialog_filters
WHERE owner_id = $1 AND filter_id = $2
`

type DeleteDialogFilterParams struct {
	OwnerID  int64
	FilterID int16
}

func (q *Queries) DeleteDialogFilter(ctx context.Context, arg DeleteDialogFilterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDialogFilter, arg.OwnerID, arg.FilterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDialogFilterEntities = `-- name: DeleteDialogFilterEntities :exec
DELETE FROM user_dialog_filter_entities
WHERE owner_id = $1 AND filter_id = $2
`

type DeleteDialogFilterEntitiesParams struct {
	OwnerID  int64
	FilterID int16
}

func (q *Queries) DeleteDialogFilterEntities(ctx context.Context, arg DeleteDialogFilterEntitiesParams) error {
	_, err := q.db.Exec(ctx, deleteDialogFilterEntities, arg.OwnerID, arg.FilterID)
	return err
}

const deleteDialogFilterPeers = `-- name: DeleteDialogFilterPeers :exec
DELETE FROM user_dialog_filter_peers
WHERE owner_id = $1 AND filter_id = $2
`

type DeleteDialogFilterPeersParams struct {
	OwnerID  int64
	FilterID int16
}

func (q *Queries) DeleteDialogFilterPeers(ctx context.Context, arg DeleteDialogFilterPeersParams) error {
	_, err := q.db.Exec(ctx, deleteDialogFilterPeers, arg.OwnerID, arg.FilterID)
	return err
}

const dialogFilterChangeAt = `-- name: DialogFilterChangeAt :one
SELECT changed_at
FROM user_dialog_filter_state
WHERE owner_id = $1
`

func (q *Queries) DialogFilterChangeAt(ctx context.Context, ownerID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, dialogFilterChangeAt, ownerID)
	var changed_at pgtype.Timestamptz
	err := row.Scan(&changed_at)
	return changed_at, err
}

const dialogFilterChannelMemberships = `-- name: DialogFilterChannelMemberships :many
SELECT channel_id, user_id, role, banned_until, join_pts, date, last_post_at
FROM channel_participants
WHERE user_id = $1 AND channel_id = ANY($2::bigint[])
`

type DialogFilterChannelMembershipsParams struct {
	UserID     int64
	ChannelIds []int64
}

func (q *Queries) DialogFilterChannelMemberships(ctx context.Context, arg DialogFilterChannelMembershipsParams) ([]ChannelParticipant, error) {
	rows, err := q.db.Query(ctx, dialogFilterChannelMemberships, arg.UserID, arg.ChannelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelParticipant
	for rows.Next() {
		var i ChannelParticipant
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Role,
			&i.BannedUntil,
			&i.JoinPts,
			&i.Date,
			&i.LastPostAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dialogFilterChatMemberships = `-- name: DialogFilterChatMemberships :many
SELECT chat_id
FROM chat_participants
WHERE user_id = $1 AND chat_id = ANY($2::bigint[])
`

type DialogFilterChatMembershipsParams struct {
	UserID  int64
	ChatIds []int64
}

func (q *Queries) DialogFilterChatMemberships(ctx context.Context, arg DialogFilterChatMembershipsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, dialogFilterChatMemberships, arg.UserID, arg.ChatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var chat_id int64
		if err := rows.Scan(&chat_id); err != nil {
			return nil, err
		}
		items = append(items, chat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dialogFilterExists = `-- name: DialogFilterExists :one
SELECT EXISTS (
    SELECT 1 FROM user_dialog_filters
    WHERE owner_id = $1 AND filter_id = $2
)
`

type DialogFilterExistsParams struct {
	OwnerID  int64
	FilterID int16
}

func (q *Queries) DialogFilterExists(ctx context.Context, arg DialogFilterExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, dialogFilterExists, arg.OwnerID, arg.FilterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const dialogFilterFolderCount = `-- name: DialogFilterFolderCount :one
SELECT count(*)::integer
FROM user_dialog_filters
WHERE owner_id = $1
`

func (q *Queries) DialogFilterFolderCount(ctx context.Context, ownerID int64) (int32, error) {
	row := q.db.QueryRow(ctx, dialogFilterFolderCount, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const dialogFilterState = `-- name: DialogFilterState :one
SELECT owner_id, order_ids, changed_at, defaults_seeded
FROM user_dialog_filter_state
WHERE owner_id = $1
`

func (q *Queries) DialogFilterState(ctx context.Context, ownerID int64) (UserDialogFilterState, error) {
	row := q.db.QueryRow(ctx, dialogFilterState, ownerID)
	var i UserDialogFilterState
	err := row.Scan(
		&i.OwnerID,
		&i.OrderIds,
		&i.ChangedAt,
		&i.DefaultsSeeded,
	)
	return i, err
}

const dialogFilterStateForUpdate = `-- name: DialogFilterStateForUpdate :one
SELECT owner_id, order_ids, changed_at, defaults_seeded
FROM user_dialog_filter_state
WHERE owner_id = $1
FOR UPDATE
`

func (q *Queries) DialogFilterStateForUpdate(ctx context.Context, ownerID int64) (UserDialogFilterState, error) {
	row := q.db.QueryRow(ctx, dialogFilterStateForUpdate, ownerID)
	var i UserDialogFilterState
	err := row.Scan(
		&i.OwnerID,
		&i.OrderIds,
		&i.ChangedAt,
		&i.DefaultsSeeded,
	)
	return i, err
}

const ensureDialogFilterState = `-- name: EnsureDialogFilterState :exec
INSERT INTO user_dialog_filter_state (owner_id)
VALUES ($1)
ON CONFLICT (owner_id) DO NOTHING
`

func (q *Queries) EnsureDialogFilterState(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, ensureDialogFilterState, ownerID)
	return err
}

const insertDialogFilterEntity = `-- name: InsertDialogFilterEntity :exec
INSERT INTO user_dialog_filter_entities (
    owner_id, filter_id, entity_position, entity_offset, length, document_id
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDialogFilterEntityParams struct {
	OwnerID        int64
	FilterID       int16
	EntityPosition int16
	EntityOffset   int32
	Length         int32
	DocumentID     int64
}

func (q *Queries) InsertDialogFilterEntity(ctx context.Context, arg InsertDialogFilterEntityParams) error {
	_, err := q.db.Exec(ctx, insertDialogFilterEntity,
		arg.OwnerID,
		arg.FilterID,
		arg.EntityPosition,
		arg.EntityOffset,
		arg.Length,
		arg.DocumentID,
	)
	return err
}

const insertDialogFilterPeer = `-- name: InsertDialogFilterPeer :exec
INSERT INTO user_dialog_filter_peers (
    owner_id, filter_id, list_type, peer_type, peer_id, peer_position
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDialogFilterPeerParams struct {
	OwnerID      int64
	FilterID     int16
	ListType     int16
	PeerType     int16
	PeerID       int64
	PeerPosition int16
}

func (q *Queries) InsertDialogFilterPeer(ctx context.Context, arg InsertDialogFilterPeerParams) error {
	_, err := q.db.Exec(ctx, insertDialogFilterPeer,
		arg.OwnerID,
		arg.FilterID,
		arg.ListType,
		arg.PeerType,
		arg.PeerID,
		arg.PeerPosition,
	)
	return err
}

const listDialogFilterEntities = `-- name: ListDialogFilterEntities :many
SELECT owner_id, filter_id, entity_position, entity_offset, length, document_id
FROM user_dialog_filter_entities
WHERE owner_id = $1
ORDER BY filter_id, entity_position
`

func (q *Queries) ListDialogFilterEntities(ctx context.Context, ownerID int64) ([]UserDialogFilterEntity, error) {
	rows, err := q.db.Query(ctx, listDialogFilterEntities, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDialogFilterEntity
	for rows.Next() {
		var i UserDialogFilterEntity
		if err := rows.Scan(
			&i.OwnerID,
			&i.FilterID,
			&i.EntityPosition,
			&i.EntityOffset,
			&i.Length,
			&i.DocumentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDialogFilterPeers = `-- name: ListDialogFilterPeers :many
SELECT owner_id, filter_id, list_type, peer_type, peer_id, peer_position
FROM user_dialog_filter_peers
WHERE owner_id = $1
ORDER BY filter_id, list_type, peer_position
`

func (q *Queries) ListDialogFilterPeers(ctx context.Context, ownerID int64) ([]UserDialogFilterPeer, error) {
	rows, err := q.db.Query(ctx, listDialogFilterPeers, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDialogFilterPeer
	for rows.Next() {
		var i UserDialogFilterPeer
		if err := rows.Scan(
			&i.OwnerID,
			&i.FilterID,
			&i.ListType,
			&i.PeerType,
			&i.PeerID,
			&i.PeerPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDialogFilters = `-- name: ListDialogFilters :many
SELECT owner_id, filter_id, title, emoticon, color, contacts, non_contacts, groups, broadcasts, bots, exclude_muted, exclude_read, exclude_archived, title_noanimate
FROM user_dialog_filters
WHERE owner_id = $1
ORDER BY filter_id
`

func (q *Queries) ListDialogFilters(ctx context.Context, ownerID int64) ([]UserDialogFilter, error) {
	rows, err := q.db.Query(ctx, listDialogFilters, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDialogFilter
	for rows.Next() {
		var i UserDialogFilter
		if err := rows.Scan(
			&i.OwnerID,
			&i.FilterID,
			&i.Title,
			&i.Emoticon,
			&i.Color,
			&i.Contacts,
			&i.NonContacts,
			&i.Groups,
			&i.Broadcasts,
			&i.Bots,
			&i.ExcludeMuted,
			&i.ExcludeRead,
			&i.ExcludeArchived,
			&i.TitleNoanimate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUpdateState = `-- name: LockUpdateState :one
SELECT user_id
FROM update_state
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) LockUpdateState(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUpdateState, userID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const markDialogFilterDefaultsSeeded = `-- name: MarkDialogFilterDefaultsSeeded :exec
UPDATE user_dialog_filter_state
SET defaults_seeded = true
WHERE owner_id = $1
`

func (q *Queries) MarkDialogFilterDefaultsSeeded(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, markDialogFilterDefaultsSeeded, ownerID)
	return err
}

const notifyDialogFilterMutation = `-- name: NotifyDialogFilterMutation :exec
SELECT pg_notify('tg_dialog_filters', $1)
`

func (q *Queries) NotifyDialogFilterMutation(ctx context.Context, pgNotify string) error {
	_, err := q.db.Exec(ctx, notifyDialogFilterMutation, pgNotify)
	return err
}

const notifyDialogFilterSeed = `-- name: NotifyDialogFilterSeed :exec
SELECT pg_notify('tg_dialog_filters', 'seed|' || CAST($1 AS BIGINT)::TEXT)
`

func (q *Queries) NotifyDialogFilterSeed(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, notifyDialogFilterSeed, ownerID)
	return err
}

const upsertDialogFilter = `-- name: UpsertDialogFilter :exec
INSERT INTO user_dialog_filters (
    owner_id, filter_id, title, emoticon, color, contacts, non_contacts,
    groups, broadcasts, bots, exclude_muted, exclude_read, exclude_archived,
    title_noanimate
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14
)
ON CONFLICT (owner_id, filter_id) DO UPDATE SET
    title = EXCLUDED.title,
    emoticon = EXCLUDED.emoticon,
    color = EXCLUDED.color,
    contacts = EXCLUDED.contacts,
    non_contacts = EXCLUDED.non_contacts,
    groups = EXCLUDED.groups,
    broadcasts = EXCLUDED.broadcasts,
    bots = EXCLUDED.bots,
    exclude_muted = EXCLUDED.exclude_muted,
    exclude_read = EXCLUDED.exclude_read,
    exclude_archived = EXCLUDED.exclude_archived,
    title_noanimate = EXCLUDED.title_noanimate
`

type UpsertDialogFilterParams struct {
	OwnerID         int64
	FilterID        int16
	Title           string
	Emoticon        string
	Color           *int16
	Contacts        bool
	NonContacts     bool
	Groups          bool
	Broadcasts      bool
	Bots            bool
	ExcludeMuted    bool
	ExcludeRead     bool
	ExcludeArchived bool
	TitleNoanimate  bool
}

func (q *Queries) UpsertDialogFilter(ctx context.Context, arg UpsertDialogFilterParams) error {
	_, err := q.db.Exec(ctx, upsertDialogFilter,
		arg.OwnerID,
		arg.FilterID,
		arg.Title,
		arg.Emoticon,
		arg.Color,
		arg.Contacts,
		arg.NonContacts,
		arg.Groups,
		arg.Broadcasts,
		arg.Bots,
		arg.ExcludeMuted,
		arg.ExcludeRead,
		arg.ExcludeArchived,
		arg.TitleNoanimate,
	)
	return err
}
