// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dialogs.sql

package db

import (
	"context"
)

const advanceReadInbox = `-- name: AdvanceReadInbox :one
UPDATE dialogs SET
  read_inbox_max_id = GREATEST(read_inbox_max_id, $1::bigint),
  unread_count = (
    SELECT count(*) FROM messages m
    WHERE m.owner_id = dialogs.owner_id AND m.peer_type = dialogs.peer_type AND m.peer_id = dialogs.peer_id
      AND m.out = false AND m.deleted = false
      AND m.local_id > GREATEST(dialogs.read_inbox_max_id, $1::bigint)
  )::int
WHERE owner_id = $2::bigint AND peer_type = $3::smallint
  AND peer_id = $4::bigint
RETURNING read_inbox_max_id, unread_count
`

type AdvanceReadInboxParams struct {
	MaxID    int64
	OwnerID  int64
	PeerType int16
	PeerID   int64
}

type AdvanceReadInboxRow struct {
	ReadInboxMaxID int64
	UnreadCount    int32
}

// AdvanceReadInbox raises the reader's read_inbox_max_id monotonically and
// recomputes unread as the count of still-unread inbound messages above it.
func (q *Queries) AdvanceReadInbox(ctx context.Context, arg AdvanceReadInboxParams) (AdvanceReadInboxRow, error) {
	row := q.db.QueryRow(ctx, advanceReadInbox,
		arg.MaxID,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
	)
	var i AdvanceReadInboxRow
	err := row.Scan(&i.ReadInboxMaxID, &i.UnreadCount)
	return i, err
}

const advanceReadOutbox = `-- name: AdvanceReadOutbox :execrows
UPDATE dialogs SET read_outbox_max_id = GREATEST(read_outbox_max_id, $4)
WHERE owner_id = $1 AND peer_type = $2 AND peer_id = $3
`

type AdvanceReadOutboxParams struct {
	OwnerID         int64
	PeerType        int16
	PeerID          int64
	ReadOutboxMaxID int64
}

// AdvanceReadOutbox raises the peer's read_outbox_max_id monotonically.
func (q *Queries) AdvanceReadOutbox(ctx context.Context, arg AdvanceReadOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceReadOutbox,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.ReadOutboxMaxID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countDialogsForOwner = `-- name: CountDialogsForOwner :one
SELECT count(*)::int FROM dialogs WHERE owner_id = $1
`

// CountDialogsForOwner is the total the truncated reply advertises, so a client
// knows more pages exist. Unfiltered by offset on purpose: it is the size of the
// whole list, not of the remainder.
func (q *Queries) CountDialogsForOwner(ctx context.Context, ownerID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countDialogsForOwner, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const dialogsForOwner = `-- name: DialogsForOwner :many
SELECT owner_id, peer_id, top_message, unread_count, read_inbox_max_id, read_outbox_max_id, peer_type FROM dialogs
WHERE owner_id = $1
  AND ($2::bigint = 0 OR top_message < $2::bigint)
ORDER BY top_message DESC
LIMIT $3::int
`

type DialogsForOwnerParams struct {
	OwnerID  int64
	OffsetID int64
	Lim      int32
}

func (q *Queries) DialogsForOwner(ctx context.Context, arg DialogsForOwnerParams) ([]Dialog, error) {
	rows, err := q.db.Query(ctx, dialogsForOwner, arg.OwnerID, arg.OffsetID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dialog
	for rows.Next() {
		var i Dialog
		if err := rows.Scan(
			&i.OwnerID,
			&i.PeerID,
			&i.TopMessage,
			&i.UnreadCount,
			&i.ReadInboxMaxID,
			&i.ReadOutboxMaxID,
			&i.PeerType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDialog = `-- name: UpsertDialog :exec
INSERT INTO dialogs (owner_id, peer_type, peer_id, top_message, unread_count)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (owner_id, peer_type, peer_id) DO UPDATE
  SET top_message  = EXCLUDED.top_message,
      unread_count = dialogs.unread_count + EXCLUDED.unread_count
`

type UpsertDialogParams struct {
	OwnerID     int64
	PeerType    int16
	PeerID      int64
	TopMessage  int64
	UnreadCount int32
}

// UpsertDialog advances top_message and adds an unread delta (0 for the sender's
// outbox side, 1 for the recipient's inbox side).
func (q *Queries) UpsertDialog(ctx context.Context, arg UpsertDialogParams) error {
	_, err := q.db.Exec(ctx, upsertDialog,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.TopMessage,
		arg.UnreadCount,
	)
	return err
}
