// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: encrypted.sql

package db

import (
	"context"
)

const deleteEncryptedEventsUpTo = `-- name: DeleteEncryptedEventsUpTo :exec
DELETE FROM encrypted_events
WHERE owner_id = $1 AND qts <= $2
`

type DeleteEncryptedEventsUpToParams struct {
	OwnerID int64
	Qts     int64
}

func (q *Queries) DeleteEncryptedEventsUpTo(ctx context.Context, arg DeleteEncryptedEventsUpToParams) error {
	_, err := q.db.Exec(ctx, deleteEncryptedEventsUpTo, arg.OwnerID, arg.Qts)
	return err
}

const encryptedEventsUpTo = `-- name: EncryptedEventsUpTo :many
SELECT owner_id, qts, random_id, data FROM encrypted_events
WHERE owner_id = $1 AND qts <= $2
ORDER BY qts
`

type EncryptedEventsUpToParams struct {
	OwnerID int64
	Qts     int64
}

func (q *Queries) EncryptedEventsUpTo(ctx context.Context, arg EncryptedEventsUpToParams) ([]EncryptedEvent, error) {
	rows, err := q.db.Query(ctx, encryptedEventsUpTo, arg.OwnerID, arg.Qts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncryptedEvent
	for rows.Next() {
		var i EncryptedEvent
		if err := rows.Scan(
			&i.OwnerID,
			&i.Qts,
			&i.RandomID,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEncryptedChat = `-- name: GetEncryptedChat :one
SELECT id, access_hash, user1_id, user2_id FROM encrypted_chats WHERE id = $1
`

func (q *Queries) GetEncryptedChat(ctx context.Context, id int32) (EncryptedChat, error) {
	row := q.db.QueryRow(ctx, getEncryptedChat, id)
	var i EncryptedChat
	err := row.Scan(
		&i.ID,
		&i.AccessHash,
		&i.User1ID,
		&i.User2ID,
	)
	return i, err
}

const getQts = `-- name: GetQts :one
SELECT qts FROM update_state WHERE user_id = $1
`

func (q *Queries) GetQts(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getQts, userID)
	var qts int64
	err := row.Scan(&qts)
	return qts, err
}

const insertEncryptedChat = `-- name: InsertEncryptedChat :exec
INSERT INTO encrypted_chats (id, access_hash, user1_id, user2_id) VALUES ($1, $2, $3, $4)
ON CONFLICT (user1_id, user2_id) DO NOTHING
`

type InsertEncryptedChatParams struct {
	ID         int32
	AccessHash int64
	User1ID    int64
	User2ID    int64
}

func (q *Queries) InsertEncryptedChat(ctx context.Context, arg InsertEncryptedChatParams) error {
	_, err := q.db.Exec(ctx, insertEncryptedChat,
		arg.ID,
		arg.AccessHash,
		arg.User1ID,
		arg.User2ID,
	)
	return err
}

const insertEncryptedEvent = `-- name: InsertEncryptedEvent :exec
INSERT INTO encrypted_events (owner_id, qts, random_id, data) VALUES ($1, $2, $3, $4)
`

type InsertEncryptedEventParams struct {
	OwnerID  int64
	Qts      int64
	RandomID int64
	Data     []byte
}

func (q *Queries) InsertEncryptedEvent(ctx context.Context, arg InsertEncryptedEventParams) error {
	_, err := q.db.Exec(ctx, insertEncryptedEvent,
		arg.OwnerID,
		arg.Qts,
		arg.RandomID,
		arg.Data,
	)
	return err
}

const setQts = `-- name: SetQts :exec
UPDATE update_state SET qts = $2 WHERE user_id = $1
`

type SetQtsParams struct {
	UserID int64
	Qts    int64
}

func (q *Queries) SetQts(ctx context.Context, arg SetQtsParams) error {
	_, err := q.db.Exec(ctx, setQts, arg.UserID, arg.Qts)
	return err
}
