// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"
)

const fileForDownload = `-- name: FileForDownload :one
SELECT f.id, f.uploader_id, f.access_hash, f.size, f.mime_type, f.file_name, f.stored, f.date FROM files f
WHERE f.id = $1 AND f.access_hash = $2 AND f.stored = true
  AND (
      EXISTS (
          SELECT 1 FROM messages m
          WHERE m.owner_id = $3 AND m.file_id = f.id AND m.deleted = false
      )
      OR EXISTS (
          SELECT 1 FROM channel_messages cm
          JOIN channel_participants cp
            ON cp.channel_id = cm.channel_id AND cp.user_id = $3
          WHERE cm.file_id = f.id
            AND cm.deleted = false
            AND (cp.banned_until IS NULL OR cp.banned_until <= now())
      )
  )
`

type FileForDownloadParams struct {
	ID         int64
	AccessHash int64
	OwnerID    int64
}

// FileForDownload is the M5 download authorization gate, and it is one query on
// purpose. Matching (id, access_hash) is wire compatibility and defence in
// depth; the EXISTS is the boundary. messages is per-owner — one row per
// entitled account, and one per member on a chat fan-out — so the set of
// accounts allowed to read a file is already enumerated on disk and needs no
// separate membership model. Channels are the exception, and the second EXISTS
// is why: a channel post writes ONE channel_messages row and no per-member row
// at all, so entitlement there has to be computed from membership rather than
// read off an enumeration. banned_until is part of that computation — a banned
// member keeps their channel_participants row, and without the predicate that
// retained row would be an entitlement instead of a record, making a ban
// cosmetic for exactly the content worth exfiltrating.
//
// Consequences that follow from putting it here rather than in the handler:
// deleteMessages soft-deletes both sides, so deleting a media message actually
// revokes retrieval instead of being cosmetic; and an (id, access_hash) pair
// pasted to an account that never received the file is inert.
//
// Every rejection returns pgx.ErrNoRows, which the caller maps to ONE error.
// files.id is dense BIGSERIAL, so distinguishing "no such file" from "wrong
// hash" from "not yours" would turn this into an enumeration oracle over every
// file on the server.
func (q *Queries) FileForDownload(ctx context.Context, arg FileForDownloadParams) (File, error) {
	row := q.db.QueryRow(ctx, fileForDownload, arg.ID, arg.AccessHash, arg.OwnerID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.AccessHash,
		&i.Size,
		&i.MimeType,
		&i.FileName,
		&i.Stored,
		&i.Date,
	)
	return i, err
}

const filesByIDs = `-- name: FilesByIDs :many
SELECT id, uploader_id, access_hash, size, mime_type, file_name, stored, date FROM files WHERE id = ANY($1::bigint[]) AND stored = true
`

func (q *Queries) FilesByIDs(ctx context.Context, ids []int64) ([]File, error) {
	rows, err := q.db.Query(ctx, filesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UploaderID,
			&i.AccessHash,
			&i.Size,
			&i.MimeType,
			&i.FileName,
			&i.Stored,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (uploader_id, access_hash, size, mime_type, file_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uploader_id, access_hash, size, mime_type, file_name, stored, date
`

type InsertFileParams struct {
	UploaderID int64
	AccessHash int64
	Size       int64
	MimeType   string
	FileName   string
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.UploaderID,
		arg.AccessHash,
		arg.Size,
		arg.MimeType,
		arg.FileName,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.AccessHash,
		&i.Size,
		&i.MimeType,
		&i.FileName,
		&i.Stored,
		&i.Date,
	)
	return i, err
}

const markFileStored = `-- name: MarkFileStored :execrows
UPDATE files SET stored = true WHERE id = $1 AND stored = false
`

func (q *Queries) MarkFileStored(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markFileStored, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userStoredBytes = `-- name: UserStoredBytes :one
SELECT coalesce(sum(size), 0)::bigint FROM files WHERE uploader_id = $1
`

// UserStoredBytes is the per-account storage cap's input. With no blob deleter
// in M5 nothing decrements it, so it is a lifetime quota, not a live one.
func (q *Queries) UserStoredBytes(ctx context.Context, uploaderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, userStoredBytes, uploaderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
