// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const historyPage = `-- name: HistoryPage :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, search_vector FROM messages
WHERE owner_id = $1 AND peer_type = $2 AND peer_id = $3
  AND deleted = false
  AND ($4::bigint = 0 OR local_id < $4::bigint)
ORDER BY local_id DESC
LIMIT $5::int
`

type HistoryPageParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
	OffsetID int64
	Lim      int32
}

func (q *Queries) HistoryPage(ctx context.Context, arg HistoryPageParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, historyPage,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.OffsetID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (owner_id, local_id, peer_type, peer_id, from_id, message, out, random_id, peer_local_id,
                      fanout_id, action_type, action_user_id, file_id, reply_to_msg_id,
                      fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
`

type InsertMessageParams struct {
	OwnerID        int64
	LocalID        int64
	PeerType       int16
	PeerID         int64
	FromID         int64
	Message        string
	Out            bool
	RandomID       int64
	PeerLocalID    int64
	FanoutID       int64
	ActionType     int16
	ActionUserID   int64
	FileID         int64
	ReplyToMsgID   *int32
	FwdFromID      *int64
	FwdDate        pgtype.Timestamptz
	FwdChannelID   *int64
	FwdChannelPost *int32
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.OwnerID,
		arg.LocalID,
		arg.PeerType,
		arg.PeerID,
		arg.FromID,
		arg.Message,
		arg.Out,
		arg.RandomID,
		arg.PeerLocalID,
		arg.FanoutID,
		arg.ActionType,
		arg.ActionUserID,
		arg.FileID,
		arg.ReplyToMsgID,
		arg.FwdFromID,
		arg.FwdDate,
		arg.FwdChannelID,
		arg.FwdChannelPost,
	)
	return err
}

const messageByOwnerLocal = `-- name: MessageByOwnerLocal :one
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, search_vector FROM messages WHERE owner_id = $1 AND local_id = $2
`

type MessageByOwnerLocalParams struct {
	OwnerID int64
	LocalID int64
}

func (q *Queries) MessageByOwnerLocal(ctx context.Context, arg MessageByOwnerLocalParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageByOwnerLocal, arg.OwnerID, arg.LocalID)
	var i Message
	err := row.Scan(
		&i.OwnerID,
		&i.LocalID,
		&i.PeerID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.Out,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.PeerLocalID,
		&i.PeerType,
		&i.FanoutID,
		&i.ActionType,
		&i.ActionUserID,
		&i.FileID,
		&i.ReplyToMsgID,
		&i.FwdFromID,
		&i.FwdDate,
		&i.FwdChannelID,
		&i.FwdChannelPost,
		&i.SearchVector,
	)
	return i, err
}

const messageByRandomID = `-- name: MessageByRandomID :one
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, search_vector FROM messages WHERE owner_id = $1 AND random_id = $2 AND random_id <> 0
`

type MessageByRandomIDParams struct {
	OwnerID  int64
	RandomID int64
}

func (q *Queries) MessageByRandomID(ctx context.Context, arg MessageByRandomIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageByRandomID, arg.OwnerID, arg.RandomID)
	var i Message
	err := row.Scan(
		&i.OwnerID,
		&i.LocalID,
		&i.PeerID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.Out,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.PeerLocalID,
		&i.PeerType,
		&i.FanoutID,
		&i.ActionType,
		&i.ActionUserID,
		&i.FileID,
		&i.ReplyToMsgID,
		&i.FwdFromID,
		&i.FwdDate,
		&i.FwdChannelID,
		&i.FwdChannelPost,
		&i.SearchVector,
	)
	return i, err
}

const messagesByFanout = `-- name: MessagesByFanout :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, search_vector FROM messages
WHERE fanout_id = $1 AND fanout_id <> 0
ORDER BY owner_id
`

// MessagesByFanout returns every per-member copy of one chat message, ascending
// by owner_id so a caller can take its advisory locks in that order. The
// `fanout_id <> 0` predicate is not redundant with the equality: 0 is the "not a
// chat message" sentinel every 1:1 row carries, so a zero argument would select
// the entire table instead of nothing.
func (q *Queries) MessagesByFanout(ctx context.Context, fanoutID int64) ([]Message, error) {
	rows, err := q.db.Query(ctx, messagesByFanout, fanoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextFanoutID = `-- name: NextFanoutID :one
SELECT nextval('message_fanout_seq')::bigint AS fanout_id
`

// NextFanoutID allocates the id shared by every per-member copy of one chat
// message. One value per fan-out, never 0.
func (q *Queries) NextFanoutID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextFanoutID)
	var fanout_id int64
	err := row.Scan(&fanout_id)
	return fanout_id, err
}

const searchMessages = `-- name: SearchMessages :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, search_vector FROM messages
WHERE owner_id = $1
  AND peer_type = $2
  AND peer_id = $3
  AND deleted = false
  AND search_vector @@ plainto_tsquery('english', $4)
  AND ($5::bigint = 0 OR local_id < $5::bigint)
ORDER BY local_id DESC
LIMIT $6::int
`

type SearchMessagesParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
	Query    string
	OffsetID int64
	Lim      int32
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.Query,
		arg.OffsetID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeleted = `-- name: SetDeleted :exec
UPDATE messages SET deleted = true WHERE owner_id = $1 AND local_id = $2
`

type SetDeletedParams struct {
	OwnerID int64
	LocalID int64
}

func (q *Queries) SetDeleted(ctx context.Context, arg SetDeletedParams) error {
	_, err := q.db.Exec(ctx, setDeleted, arg.OwnerID, arg.LocalID)
	return err
}

const setEditedText = `-- name: SetEditedText :exec
UPDATE messages SET message = $3, edit_date = now() WHERE owner_id = $1 AND local_id = $2
`

type SetEditedTextParams struct {
	OwnerID int64
	LocalID int64
	Message string
}

func (q *Queries) SetEditedText(ctx context.Context, arg SetEditedTextParams) error {
	_, err := q.db.Exec(ctx, setEditedText, arg.OwnerID, arg.LocalID, arg.Message)
	return err
}
