// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
)

const historyPage = `-- name: HistoryPage :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id FROM messages
WHERE owner_id = $1 AND peer_id = $2 AND deleted = false
  AND ($3::bigint = 0 OR local_id < $3::bigint)
ORDER BY local_id DESC
LIMIT $4::int
`

type HistoryPageParams struct {
	OwnerID  int64
	PeerID   int64
	OffsetID int64
	Lim      int32
}

func (q *Queries) HistoryPage(ctx context.Context, arg HistoryPageParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, historyPage,
		arg.OwnerID,
		arg.PeerID,
		arg.OffsetID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (owner_id, local_id, peer_id, from_id, message, out, random_id, peer_local_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertMessageParams struct {
	OwnerID     int64
	LocalID     int64
	PeerID      int64
	FromID      int64
	Message     string
	Out         bool
	RandomID    int64
	PeerLocalID int64
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.OwnerID,
		arg.LocalID,
		arg.PeerID,
		arg.FromID,
		arg.Message,
		arg.Out,
		arg.RandomID,
		arg.PeerLocalID,
	)
	return err
}

const messageByOwnerLocal = `-- name: MessageByOwnerLocal :one
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id FROM messages WHERE owner_id = $1 AND local_id = $2
`

type MessageByOwnerLocalParams struct {
	OwnerID int64
	LocalID int64
}

func (q *Queries) MessageByOwnerLocal(ctx context.Context, arg MessageByOwnerLocalParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageByOwnerLocal, arg.OwnerID, arg.LocalID)
	var i Message
	err := row.Scan(
		&i.OwnerID,
		&i.LocalID,
		&i.PeerID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.Out,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.PeerLocalID,
	)
	return i, err
}

const messageByRandomID = `-- name: MessageByRandomID :one
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id FROM messages WHERE owner_id = $1 AND random_id = $2 AND random_id <> 0
`

type MessageByRandomIDParams struct {
	OwnerID  int64
	RandomID int64
}

func (q *Queries) MessageByRandomID(ctx context.Context, arg MessageByRandomIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageByRandomID, arg.OwnerID, arg.RandomID)
	var i Message
	err := row.Scan(
		&i.OwnerID,
		&i.LocalID,
		&i.PeerID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.Out,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.PeerLocalID,
	)
	return i, err
}

const setDeleted = `-- name: SetDeleted :exec
UPDATE messages SET deleted = true WHERE owner_id = $1 AND local_id = $2
`

type SetDeletedParams struct {
	OwnerID int64
	LocalID int64
}

func (q *Queries) SetDeleted(ctx context.Context, arg SetDeletedParams) error {
	_, err := q.db.Exec(ctx, setDeleted, arg.OwnerID, arg.LocalID)
	return err
}

const setEditedText = `-- name: SetEditedText :exec
UPDATE messages SET message = $3, edit_date = now() WHERE owner_id = $1 AND local_id = $2
`

type SetEditedTextParams struct {
	OwnerID int64
	LocalID int64
	Message string
}

func (q *Queries) SetEditedText(ctx context.Context, arg SetEditedTextParams) error {
	_, err := q.db.Exec(ctx, setEditedText, arg.OwnerID, arg.LocalID, arg.Message)
	return err
}
