// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthKey struct {
	ID            int64
	KeyValue      []byte
	UserID        *int64
	CreatedAt     pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	PendingUserID *int64
}

type Channel struct {
	ID        int64
	Title     string
	About     string
	CreatorID int64
	Megagroup bool
	Version   int32
	Date      pgtype.Timestamptz
}

type ChannelEvent struct {
	ChannelID int64
	Pts       int64
	Type      int16
	LocalID   int64
}

type ChannelInvite struct {
	Hash      string
	ChannelID int64
	CreatorID int64
	Date      pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type ChannelMessage struct {
	ChannelID int64
	LocalID   int64
	FromID    int64
	Date      pgtype.Timestamptz
	Message   string
	EditDate  pgtype.Timestamptz
	Deleted   bool
	RandomID  int64
	FileID    *int64
}

type ChannelParticipant struct {
	ChannelID   int64
	UserID      int64
	Role        int16
	BannedUntil pgtype.Timestamptz
	JoinPts     int64
	Date        pgtype.Timestamptz
}

type ChannelState struct {
	ChannelID   int64
	Pts         int64
	NextLocalID int64
	Date        pgtype.Timestamptz
}

type Chat struct {
	ID        int64
	Title     string
	CreatorID int64
	Version   int32
	Date      pgtype.Timestamptz
}

type ChatParticipant struct {
	ChatID    int64
	UserID    int64
	InviterID int64
	Date      pgtype.Timestamptz
}

type Dialog struct {
	OwnerID         int64
	PeerID          int64
	TopMessage      int64
	UnreadCount     int32
	ReadInboxMaxID  int64
	ReadOutboxMaxID int64
	PeerType        int16
}

type File struct {
	ID         int64
	UploaderID int64
	AccessHash int64
	Size       int64
	MimeType   string
	FileName   string
	Stored     bool
	Date       pgtype.Timestamptz
}

type Message struct {
	OwnerID      int64
	LocalID      int64
	PeerID       int64
	FromID       int64
	Date         pgtype.Timestamptz
	Message      string
	Out          bool
	EditDate     pgtype.Timestamptz
	Deleted      bool
	RandomID     int64
	PeerLocalID  int64
	PeerType     int16
	FanoutID     int64
	ActionType   int16
	ActionUserID int64
	FileID       int64
}

type MessageEvent struct {
	OwnerID int64
	Pts     int64
	Type    int16
	LocalID int64
}

type PhoneCode struct {
	Phone      string
	CodeHash   string
	Code       string
	ExpiresAt  pgtype.Timestamptz
	Attempts   int32
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type UpdateState struct {
	UserID      int64
	Pts         int64
	Seq         int64
	Date        pgtype.Timestamptz
	NextLocalID int64
}

type UploadPart struct {
	UserID    int64
	FileID    int64
	PartIndex int32
	Payload   []byte
	Date      pgtype.Timestamptz
}

type User struct {
	ID        int64
	Phone     string
	FirstName string
	LastName  string
	CreatedAt pgtype.Timestamptz
}

type UserPassword struct {
	UserID        int64
	Salt1         []byte
	Salt2         []byte
	Verifier      []byte
	Hint          string
	RecoveryEmail *string
	HasRecovery   bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
