// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthKey struct {
	ID         int64
	KeyValue   []byte
	UserID     *int64
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

type PhoneCode struct {
	Phone     string
	CodeHash  string
	Code      string
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID        int64
	Phone     string
	FirstName string
	LastName  string
	CreatedAt pgtype.Timestamptz
}
