// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passwords.sql

package db

import (
	"context"
)

const deletePassword = `-- name: DeletePassword :execrows
DELETE FROM user_passwords WHERE user_id = $1
`

func (q *Queries) DeletePassword(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePassword, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const passwordByUser = `-- name: PasswordByUser :one
SELECT user_id, salt1, salt2, verifier, hint, recovery_email, has_recovery, created_at, updated_at FROM user_passwords WHERE user_id = $1
`

func (q *Queries) PasswordByUser(ctx context.Context, userID int64) (UserPassword, error) {
	row := q.db.QueryRow(ctx, passwordByUser, userID)
	var i UserPassword
	err := row.Scan(
		&i.UserID,
		&i.Salt1,
		&i.Salt2,
		&i.Verifier,
		&i.Hint,
		&i.RecoveryEmail,
		&i.HasRecovery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPassword = `-- name: UpsertPassword :exec
INSERT INTO user_passwords (user_id, salt1, salt2, verifier, hint, recovery_email, has_recovery)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) DO UPDATE
  SET salt1          = EXCLUDED.salt1,
      salt2          = EXCLUDED.salt2,
      verifier       = EXCLUDED.verifier,
      hint           = EXCLUDED.hint,
      recovery_email = EXCLUDED.recovery_email,
      has_recovery   = EXCLUDED.has_recovery,
      updated_at     = now()
`

type UpsertPasswordParams struct {
	UserID        int64
	Salt1         []byte
	Salt2         []byte
	Verifier      []byte
	Hint          string
	RecoveryEmail *string
	HasRecovery   bool
}

func (q *Queries) UpsertPassword(ctx context.Context, arg UpsertPasswordParams) error {
	_, err := q.db.Exec(ctx, upsertPassword,
		arg.UserID,
		arg.Salt1,
		arg.Salt2,
		arg.Verifier,
		arg.Hint,
		arg.RecoveryEmail,
		arg.HasRecovery,
	)
	return err
}
