// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: peer_dialogs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chatParticipantsByChatIDs = `-- name: ChatParticipantsByChatIDs :many
SELECT chat_id, user_id, inviter_id, date FROM chat_participants
WHERE chat_id = ANY($1::bigint[])
ORDER BY chat_id, user_id
`

func (q *Queries) ChatParticipantsByChatIDs(ctx context.Context, chatIds []int64) ([]ChatParticipant, error) {
	rows, err := q.db.Query(ctx, chatParticipantsByChatIDs, chatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatParticipant
	for rows.Next() {
		var i ChatParticipant
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.InviterID,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatsByIDs = `-- name: ChatsByIDs :many
SELECT id, title, creator_id, version, date, pinned_message_id, default_banned_rights FROM chats
WHERE id = ANY($1::bigint[])
`

func (q *Queries) ChatsByIDs(ctx context.Context, chatIds []int64) ([]Chat, error) {
	rows, err := q.db.Query(ctx, chatsByIDs, chatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatorID,
			&i.Version,
			&i.Date,
			&i.PinnedMessageID,
			&i.DefaultBannedRights,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesByOwnerLocals = `-- name: MessagesByOwnerLocals :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, message_tsv FROM messages
WHERE owner_id = $1::bigint
  AND local_id = ANY($2::bigint[])
`

type MessagesByOwnerLocalsParams struct {
	OwnerID  int64
	LocalIds []int64
}

func (q *Queries) MessagesByOwnerLocals(ctx context.Context, arg MessagesByOwnerLocalsParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, messagesByOwnerLocals, arg.OwnerID, arg.LocalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const peerChannelDialogsForOwner = `-- name: PeerChannelDialogsForOwner :many
SELECT
    c.id AS channel_id,
    c.title AS channel_title,
    c.about AS channel_about,
    c.creator_id AS channel_creator_id,
    c.megagroup AS channel_megagroup,
    c.version AS channel_version,
    c.date AS channel_date,
    c.pinned_message_id AS channel_pinned_message_id,
    c.username AS channel_username,
    c.default_banned_rights AS channel_default_banned_rights,
    p.role AS member_role,
    p.banned_until AS member_banned_until,
    p.join_pts AS member_join_pts,
    COALESCE(read_state.read_max_id, 0)::bigint AS read_inbox_max_id,
    unread.unread_count,
    cs.pts AS channel_pts,
    top.local_id AS top_local_id,
    top.from_id AS top_from_id,
    top.date AS top_date,
    top.message AS top_message,
    top.edit_date AS top_edit_date,
    top.random_id AS top_random_id,
    top.file_id AS top_file_id,
    top.reply_to_msg_id AS top_reply_to_msg_id,
    top.action_type AS top_action_type
FROM channels c
JOIN channel_participants p ON p.channel_id = c.id
JOIN channel_state cs ON cs.channel_id = c.id
LEFT JOIN channel_read_state read_state
  ON read_state.channel_id = c.id AND read_state.user_id = p.user_id
LEFT JOIN LATERAL (
    SELECT LEAST(
        count(*) FILTER (WHERE unread_posts.from_id <> p.user_id AND NOT unread_posts.deleted),
        1000
    )::int AS unread_count
    FROM (
        SELECT cm.local_id, cm.from_id, cm.deleted
        FROM channel_messages cm
        WHERE cm.channel_id = c.id
          AND cm.local_id > COALESCE(read_state.read_max_id, 0)
        ORDER BY cm.local_id
        LIMIT 1001
    ) unread_posts
) unread ON true
JOIN LATERAL (
    SELECT cm.local_id, cm.from_id, cm.date, cm.message, cm.edit_date,
           cm.random_id, cm.file_id, cm.reply_to_msg_id, cm.action_type
    FROM channel_messages cm
    WHERE cm.channel_id = c.id AND cm.deleted = false
    ORDER BY cm.local_id DESC
    LIMIT 1
) top ON true
WHERE c.id = ANY($1::bigint[])
  AND p.user_id = $2::bigint
  AND (p.banned_until IS NULL OR p.banned_until <= now())
`

type PeerChannelDialogsForOwnerParams struct {
	ChannelIds []int64
	OwnerID    int64
}

type PeerChannelDialogsForOwnerRow struct {
	ChannelID                  int64
	ChannelTitle               string
	ChannelAbout               string
	ChannelCreatorID           int64
	ChannelMegagroup           bool
	ChannelVersion             int32
	ChannelDate                pgtype.Timestamptz
	ChannelPinnedMessageID     *int32
	ChannelUsername            *string
	ChannelDefaultBannedRights []string
	MemberRole                 int16
	MemberBannedUntil          pgtype.Timestamptz
	MemberJoinPts              int64
	ReadInboxMaxID             int64
	UnreadCount                int32
	ChannelPts                 int64
	TopLocalID                 int64
	TopFromID                  int64
	TopDate                    pgtype.Timestamptz
	TopMessage                 string
	TopEditDate                pgtype.Timestamptz
	TopRandomID                int64
	TopFileID                  *int64
	TopReplyToMsgID            *int32
	TopActionType              int16
}

// PeerChannelDialogsForOwner is the channel counterpart of
// PeerDialogsForOwner. A channel has no dialogs row; its current, unbanned
// membership and newest live post are the dialog selection. The membership
// predicate and top-post lookup are in this one statement so the selected post
// can never come from a channel the viewer is not entitled to read in the same
// snapshot.
func (q *Queries) PeerChannelDialogsForOwner(ctx context.Context, arg PeerChannelDialogsForOwnerParams) ([]PeerChannelDialogsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, peerChannelDialogsForOwner, arg.ChannelIds, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeerChannelDialogsForOwnerRow
	for rows.Next() {
		var i PeerChannelDialogsForOwnerRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelTitle,
			&i.ChannelAbout,
			&i.ChannelCreatorID,
			&i.ChannelMegagroup,
			&i.ChannelVersion,
			&i.ChannelDate,
			&i.ChannelPinnedMessageID,
			&i.ChannelUsername,
			&i.ChannelDefaultBannedRights,
			&i.MemberRole,
			&i.MemberBannedUntil,
			&i.MemberJoinPts,
			&i.ReadInboxMaxID,
			&i.UnreadCount,
			&i.ChannelPts,
			&i.TopLocalID,
			&i.TopFromID,
			&i.TopDate,
			&i.TopMessage,
			&i.TopEditDate,
			&i.TopRandomID,
			&i.TopFileID,
			&i.TopReplyToMsgID,
			&i.TopActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const peerDialogsForOwner = `-- name: PeerDialogsForOwner :many
SELECT owner_id, peer_id, top_message, unread_count, read_inbox_max_id, read_outbox_max_id, peer_type FROM dialogs
WHERE owner_id = $1::bigint
  AND (
    (peer_type = 1 AND peer_id = ANY($2::bigint[]))
    OR (peer_type = 2 AND peer_id = ANY($3::bigint[]))
  )
`

type PeerDialogsForOwnerParams struct {
	OwnerID int64
	UserIds []int64
	ChatIds []int64
}

// PeerDialogsForOwner selects only owner-scoped basic dialogs named by the
// caller. The peer-type predicates stay separate so a user id and a chat id
// with the same numeric value cannot cross-match.
func (q *Queries) PeerDialogsForOwner(ctx context.Context, arg PeerDialogsForOwnerParams) ([]Dialog, error) {
	rows, err := q.db.Query(ctx, peerDialogsForOwner, arg.OwnerID, arg.UserIds, arg.ChatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dialog
	for rows.Next() {
		var i Dialog
		if err := rows.Scan(
			&i.OwnerID,
			&i.PeerID,
			&i.TopMessage,
			&i.UnreadCount,
			&i.ReadInboxMaxID,
			&i.ReadOutboxMaxID,
			&i.PeerType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unreadCountForOwner = `-- name: UnreadCountForOwner :one
SELECT ((
    SELECT COALESCE(SUM(d.unread_count), 0)
    FROM dialogs d
    WHERE d.owner_id = $1::bigint
) + (
    SELECT COALESCE(SUM(unread.unread_count), 0)
    FROM channel_participants p
    LEFT JOIN channel_read_state read_state
      ON read_state.channel_id = p.channel_id AND read_state.user_id = p.user_id
    CROSS JOIN LATERAL (
        SELECT LEAST(
            count(*) FILTER (WHERE unread_posts.from_id <> p.user_id AND NOT unread_posts.deleted),
            1000
        )::bigint AS unread_count
        FROM (
            SELECT cm.local_id, cm.from_id, cm.deleted
            FROM channel_messages cm
            WHERE cm.channel_id = p.channel_id
              AND cm.local_id > COALESCE(read_state.read_max_id, 0)
            ORDER BY cm.local_id
            LIMIT 1001
        ) unread_posts
    ) unread
    WHERE p.user_id = $1::bigint
      AND (p.banned_until IS NULL OR p.banned_until <= now())
))::bigint
`

func (q *Queries) UnreadCountForOwner(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, unreadCountForOwner, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
