// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phone_lookups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPhoneLookups = `-- name: CountPhoneLookups :one
SELECT COUNT(DISTINCT phone)
FROM phone_lookups
WHERE caller_id = $1
  AND looked_up_at >= $2
`

type CountPhoneLookupsParams struct {
	CallerID   int64
	LookedUpAt pgtype.Timestamptz
}

// Count distinct phones looked up by caller_id since the cutoff.
func (q *Queries) CountPhoneLookups(ctx context.Context, arg CountPhoneLookupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPhoneLookups, arg.CallerID, arg.LookedUpAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredPhoneLookups = `-- name: DeleteExpiredPhoneLookups :exec
DELETE FROM phone_lookups
WHERE looked_up_at < $1
`

// Remove lookups older than the window so the table does not grow unbounded.
func (q *Queries) DeleteExpiredPhoneLookups(ctx context.Context, lookedUpAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredPhoneLookups, lookedUpAt)
	return err
}

const insertPhoneLookup = `-- name: InsertPhoneLookup :exec
INSERT INTO phone_lookups (caller_id, phone, looked_up_at)
VALUES ($1, $2, now())
ON CONFLICT DO NOTHING
`

type InsertPhoneLookupParams struct {
	CallerID int64
	Phone    string
}

// Record a lookup attempt. caller_id and phone are the normalized values.
func (q *Queries) InsertPhoneLookup(ctx context.Context, arg InsertPhoneLookupParams) error {
	_, err := q.db.Exec(ctx, insertPhoneLookup, arg.CallerID, arg.Phone)
	return err
}
