// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chargeRateLimit = `-- name: ChargeRateLimit :exec
INSERT INTO rate_limits (subject_id, surface, token_count, window_start, expires_at)
VALUES ($1, $2, 1, now(), now() + $3::INTERVAL)
ON CONFLICT (subject_id, surface) DO UPDATE SET
    token_count = CASE
        WHEN rate_limits.expires_at <= now() THEN 1
        ELSE rate_limits.token_count + 1
    END,
    window_start = CASE
        WHEN rate_limits.expires_at <= now() THEN now()
        ELSE rate_limits.window_start
    END,
    expires_at = CASE
        WHEN rate_limits.expires_at <= now() THEN now() + $3::INTERVAL
        ELSE rate_limits.expires_at
    END
`

type ChargeRateLimitParams struct {
	SubjectID int64
	Surface   string
	Column3   pgtype.Interval
}

// Charge a rate-limit counter after a failed attempt. Uses the same
// INSERT ... ON CONFLICT pattern as TryConsumeRateLimit but is called only
// after a failure, so it always increments (or seeds at 1).
func (q *Queries) ChargeRateLimit(ctx context.Context, arg ChargeRateLimitParams) error {
	_, err := q.db.Exec(ctx, chargeRateLimit, arg.SubjectID, arg.Surface, arg.Column3)
	return err
}

const checkRateLimitBudget = `-- name: CheckRateLimitBudget :one
SELECT token_count, expires_at
FROM rate_limits
WHERE subject_id = $1
  AND surface = $2
`

type CheckRateLimitBudgetParams struct {
	SubjectID int64
	Surface   string
}

type CheckRateLimitBudgetRow struct {
	TokenCount int32
	ExpiresAt  pgtype.Timestamptz
}

// Read-only check of the current budget for a subject/surface pair.
// Returns the current token count and expiry deadline so the caller can decide
// whether to proceed without consuming a token.
// Returns pgx.ErrNoRows when no row exists (budget not yet exhausted).
func (q *Queries) CheckRateLimitBudget(ctx context.Context, arg CheckRateLimitBudgetParams) (CheckRateLimitBudgetRow, error) {
	row := q.db.QueryRow(ctx, checkRateLimitBudget, arg.SubjectID, arg.Surface)
	var i CheckRateLimitBudgetRow
	err := row.Scan(&i.TokenCount, &i.ExpiresAt)
	return i, err
}

const getRateLimitExpiresAt = `-- name: GetRateLimitExpiresAt :one
SELECT expires_at
FROM rate_limits
WHERE subject_id = $1
  AND surface = $2
`

type GetRateLimitExpiresAtParams struct {
	SubjectID int64
	Surface   string
}

// Read the expiry deadline for a denied rate-limit check.
// Called after TryConsumeRateLimit returns ErrNoRows to compute the wait time.
// Uses a fresh READ COMMITTED snapshot so it sees the row committed by the
// concurrent transaction that won the race.
func (q *Queries) GetRateLimitExpiresAt(ctx context.Context, arg GetRateLimitExpiresAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getRateLimitExpiresAt, arg.SubjectID, arg.Surface)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const sweepExpiredRateLimits = `-- name: SweepExpiredRateLimits :execrows
DELETE FROM rate_limits
WHERE expires_at < now()
`

// Delete rows whose per-row expiry deadline has passed. The deadline is stored
// on the row (expires_at = window_start + window), so the sweep does not need
// to know per-surface window durations. The return value reports rows affected.
func (q *Queries) SweepExpiredRateLimits(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredRateLimits)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryConsumeRateLimit = `-- name: TryConsumeRateLimit :one
INSERT INTO rate_limits (subject_id, surface, token_count, window_start, expires_at)
VALUES ($1, $2, 1, now(), now() + $3::INTERVAL)
ON CONFLICT (subject_id, surface) DO UPDATE SET
    token_count = CASE
        WHEN rate_limits.expires_at <= now() THEN 1
        ELSE rate_limits.token_count + 1
    END,
    window_start = CASE
        WHEN rate_limits.expires_at <= now() THEN now()
        ELSE rate_limits.window_start
    END,
    expires_at = CASE
        WHEN rate_limits.expires_at <= now() THEN now() + $3::INTERVAL
        ELSE rate_limits.expires_at
    END
WHERE rate_limits.expires_at <= now()
   OR rate_limits.token_count < $4
RETURNING token_count, window_start, expires_at
`

type TryConsumeRateLimitParams struct {
	SubjectID  int64
	Surface    string
	Column3    pgtype.Interval
	TokenCount int32
}

type TryConsumeRateLimitRow struct {
	TokenCount  int32
	WindowStart pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

// Attempt to consume a rate-limit token.
//
// INSERT seeds a new counter; ON CONFLICT fires the DO UPDATE:
//   - Window closed: reset count=1, window_start=now, expires_at=now+window.
//   - Window open, under limit: bump count.
//   - Window open, at limit: the WHERE clause prevents the UPDATE entirely.
//
// Whether the window is closed is read from expires_at, the deadline stored
// when the window opened, and never recomputed as window_start + the current
// config. That is the one boundary the sweep can also see, and the two must
// agree: derive it from the live config instead and changing the config splits
// them, so the sweep collects a row the limiter is still counting against and
// the subject silently gets a fresh budget. The consequence is deliberate — a
// config change takes effect at the next window rather than mid-flight, in
// either direction, and never grants a subject more than the window it opened
// with.
//
// Returns one row (from RETURNING) when the request is allowed.
// Returns pgx.ErrNoRows when the request is denied (UPDATE prevented by WHERE).
//
// Exactness under concurrency comes from the row-level lock taken by
// INSERT ... ON CONFLICT — different subjects never block each other.
func (q *Queries) TryConsumeRateLimit(ctx context.Context, arg TryConsumeRateLimitParams) (TryConsumeRateLimitRow, error) {
	row := q.db.QueryRow(ctx, tryConsumeRateLimit,
		arg.SubjectID,
		arg.Surface,
		arg.Column3,
		arg.TokenCount,
	)
	var i TryConsumeRateLimitRow
	err := row.Scan(&i.TokenCount, &i.WindowStart, &i.ExpiresAt)
	return i, err
}
