// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAndConsumeRateLimit = `-- name: CheckAndConsumeRateLimit :one
INSERT INTO rate_limits (subject_id, surface, token_count, window_start, consumed)
VALUES ($1, $2, 1, now(), true)
ON CONFLICT (subject_id, surface) DO UPDATE SET
    token_count = CASE
        WHEN now() - rate_limits.window_start >= $3::INTERVAL THEN 1
        WHEN rate_limits.token_count < $4 THEN rate_limits.token_count + 1
        ELSE rate_limits.token_count
    END,
    window_start = CASE
        WHEN now() - rate_limits.window_start >= $3::INTERVAL THEN now()
        ELSE rate_limits.window_start
    END,
    consumed = CASE
        WHEN now() - rate_limits.window_start >= $3::INTERVAL THEN true
        WHEN rate_limits.token_count < $4 THEN true
        ELSE false
    END
WHERE now() - rate_limits.window_start >= $3::INTERVAL
   OR rate_limits.token_count < $4
RETURNING token_count, window_start, consumed
`

type CheckAndConsumeRateLimitParams struct {
	SubjectID  int64
	Surface    string
	Column3    pgtype.Interval
	TokenCount int32
}

type CheckAndConsumeRateLimitRow struct {
	TokenCount  int32
	WindowStart pgtype.Timestamptz
	Consumed    bool
}

// Atomic check-and-consume on a rate-limit counter.
//
// INSERT attempts to seed a new counter; ON CONFLICT fires the DO UPDATE:
//  1. If the window has expired, reset to count=1, window_start=now.
//  2. If the window is active and count < limit, bump count.
//  3. If the window is active and count >= limit, the WHERE clause prevents
//     the UPDATE — the existing (unchanged) row is returned instead.
//
// The RETURNING clause always produces one row. The caller checks
// consumed=true to distinguish "allowed" from "denied".
//
// Exactness under concurrency comes from the row-level lock taken by
// INSERT ... ON CONFLICT — no advisory lock needed.
func (q *Queries) CheckAndConsumeRateLimit(ctx context.Context, arg CheckAndConsumeRateLimitParams) (CheckAndConsumeRateLimitRow, error) {
	row := q.db.QueryRow(ctx, checkAndConsumeRateLimit,
		arg.SubjectID,
		arg.Surface,
		arg.Column3,
		arg.TokenCount,
	)
	var i CheckAndConsumeRateLimitRow
	err := row.Scan(&i.TokenCount, &i.WindowStart, &i.Consumed)
	return i, err
}

const sweepExpiredRateLimits = `-- name: SweepExpiredRateLimits :exec
DELETE FROM rate_limits
WHERE window_start + $1::INTERVAL < now()
`

// Delete rows whose window has fully expired (window_start + window < now).
// Prevents unbounded growth of stale subject entries.
func (q *Queries) SweepExpiredRateLimits(ctx context.Context, dollar_1 pgtype.Interval) error {
	_, err := q.db.Exec(ctx, sweepExpiredRateLimits, dollar_1)
	return err
}
