// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAndConsumeRateLimit = `-- name: CheckAndConsumeRateLimit :one
WITH upsert AS (
    INSERT INTO rate_limits (subject_id, surface, token_count, window_start, expires_at)
    VALUES ($1, $2, 1, now(), now() + $3::INTERVAL)
    ON CONFLICT (subject_id, surface) DO UPDATE SET
        token_count = CASE
            WHEN now() - rate_limits.window_start >= $3::INTERVAL THEN 1
            WHEN rate_limits.token_count < $4 THEN rate_limits.token_count + 1
            ELSE rate_limits.token_count
        END,
        window_start = CASE
            WHEN now() - rate_limits.window_start >= $3::INTERVAL THEN now()
            ELSE rate_limits.window_start
        END,
        expires_at = CASE
            WHEN now() - rate_limits.window_start >= $3::INTERVAL THEN now() + $3::INTERVAL
            ELSE rate_limits.expires_at
        END
    WHERE now() - rate_limits.window_start >= $3::INTERVAL
       OR rate_limits.token_count < $4
    RETURNING token_count, window_start, expires_at
)
SELECT token_count, window_start, expires_at, true AS consumed
FROM upsert
UNION ALL
SELECT rl.token_count, rl.window_start, rl.expires_at, false
FROM rate_limits rl
WHERE rl.subject_id = $1 AND rl.surface = $2
  AND NOT EXISTS (SELECT 1 FROM upsert)
LIMIT 1
`

type CheckAndConsumeRateLimitParams struct {
	SubjectID  int64
	Surface    string
	Column3    pgtype.Interval
	TokenCount int32
}

type CheckAndConsumeRateLimitRow struct {
	TokenCount  int32
	WindowStart pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	Consumed    bool
}

// Atomic check-and-consume on a rate-limit counter. Single query, no advisory lock.
//
// Phase 1 (upsert CTE): INSERT seeds a new counter; ON CONFLICT fires the DO UPDATE:
//
//   - Window expired: reset count=1, window_start=now, expires_at=now+window.
//
//   - Window active, under limit: bump count.
//
//   - Window active, at limit: the WHERE clause prevents the UPDATE entirely.
//
//     The RETURNING clause fires for both INSERT and successful UPDATE. When the
//     UPDATE is prevented (at limit), the CTE produces no row.
//
// Phase 2 (SELECT): If the CTE returned a row, the request was allowed and the
//
//	row carries the new state. If the CTE produced nothing, fall back to reading
//	the existing row to compute the remaining wait — the request is denied.
//
// Exactness under concurrency comes from the row-level lock taken by
// INSERT ... ON CONFLICT — different subjects never block each other.
func (q *Queries) CheckAndConsumeRateLimit(ctx context.Context, arg CheckAndConsumeRateLimitParams) (CheckAndConsumeRateLimitRow, error) {
	row := q.db.QueryRow(ctx, checkAndConsumeRateLimit,
		arg.SubjectID,
		arg.Surface,
		arg.Column3,
		arg.TokenCount,
	)
	var i CheckAndConsumeRateLimitRow
	err := row.Scan(
		&i.TokenCount,
		&i.WindowStart,
		&i.ExpiresAt,
		&i.Consumed,
	)
	return i, err
}

const sweepExpiredRateLimits = `-- name: SweepExpiredRateLimits :exec
DELETE FROM rate_limits
WHERE expires_at < now()
`

// Delete rows whose per-row expiry deadline has passed. The deadline is stored
// on the row (expires_at = window_start + window), so the sweep does not need
// to know per-surface window durations.
func (q *Queries) SweepExpiredRateLimits(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sweepExpiredRateLimits)
	return err
}
