// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: searchglobal.sql

package db

import (
	"context"
)

const ownedMessagesByLocalIDs = `-- name: OwnedMessagesByLocalIDs :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, message_tsv FROM messages
WHERE owner_id = $1
  AND local_id = ANY($2::bigint[])
  AND deleted = false
`

type OwnedMessagesByLocalIDsParams struct {
	OwnerID  int64
	LocalIds []int64
}

// OwnedMessagesByLocalIDs hydrates the owned arm of a search page. The owner_id
// predicate is repeated here rather than trusted from the page query: this is
// the query that reads message bodies, so it carries the predicate that decides
// who may read them.
func (q *Queries) OwnedMessagesByLocalIDs(ctx context.Context, arg OwnedMessagesByLocalIDsParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, ownedMessagesByLocalIDs, arg.OwnerID, arg.LocalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGlobalPage = `-- name: SearchGlobalPage :many
WITH owned AS (
    SELECT FLOOR(EXTRACT(EPOCH FROM date))::bigint AS rate,
           peer_type                               AS peer_type,
           peer_id                                 AS peer_id,
           local_id                                AS msg_id
    FROM messages
    WHERE owner_id = $2
      AND peer_type IN (1, 2)
      AND deleted = false
      AND message_tsv @@ plainto_tsquery('simple', $3)
      AND ($4::bool = false
           OR (FLOOR(EXTRACT(EPOCH FROM date))::bigint, peer_type, peer_id, local_id)
              < ($5::bigint, $6::smallint,
                 $7::bigint, $8::bigint))
    ORDER BY rate DESC, peer_type DESC, peer_id DESC, msg_id DESC
    LIMIT $1::int
), posts AS (
    SELECT FLOOR(EXTRACT(EPOCH FROM cm.date))::bigint AS rate,
           3::smallint                                AS peer_type,
           cm.channel_id                              AS peer_id,
           cm.local_id                                AS msg_id
    FROM channel_messages cm
    WHERE cm.deleted = false
      AND cm.message_tsv @@ plainto_tsquery('simple', $3)
      AND EXISTS (
          SELECT 1 FROM channel_participants cp
          WHERE cp.channel_id = cm.channel_id
            AND cp.user_id = $2
            AND (cp.banned_until IS NULL OR cp.banned_until <= now())
      )
      AND ($4::bool = false
           OR (FLOOR(EXTRACT(EPOCH FROM cm.date))::bigint, 3::smallint, cm.channel_id, cm.local_id)
              < ($5::bigint, $6::smallint,
                 $7::bigint, $8::bigint))
    ORDER BY rate DESC, peer_type DESC, peer_id DESC, msg_id DESC
    LIMIT $1::int
)
SELECT rate, peer_type, peer_id, msg_id
FROM (SELECT rate, peer_type, peer_id, msg_id FROM owned UNION ALL SELECT rate, peer_type, peer_id, msg_id FROM posts) hits
ORDER BY rate DESC, peer_type DESC, peer_id DESC, msg_id DESC
LIMIT $1::int
`

type SearchGlobalPageParams struct {
	Lim            int32
	OwnerID        int64
	Query          string
	HasCursor      bool
	OffsetRate     int64
	OffsetPeerType int16
	OffsetPeerID   int64
	OffsetID       int64
}

type SearchGlobalPageRow struct {
	Rate     int64
	PeerType int16
	PeerID   int64
	MsgID    int64
}

// SearchGlobalPage returns one ordered page of cross-dialog search keys: which
// peer each hit belongs to and its id in that peer's id space. It names rows
// rather than returning them because the two arms read tables with different
// shapes; the callers hydrate each arm through its own query.
//
// The two arms are the two authorization predicates, and neither may be relaxed
// to make the composition uniform. Owned rows (peer_type 1 = user, 2 = chat) are
// filtered by owner_id: a chat keeps one copy per member, so ownership already
// is the membership check. Channel posts keep one shared row per post, so they
// carry the membership predicate explicitly, as an EXISTS over
// channel_participants including the banned_until clause — a plain join on
// membership would keep serving posts to a banned member.
//
// Ordering is newest-first by (rate, peer, id), where rate is the message date
// truncated to whole seconds — the same value offset_rate carries on the wire.
// Truncating in the sort key rather than only in the emitted cursor is what
// makes paging exact: a sub-second ordering the cursor cannot express would skip
// every row that shares its second with the last row of a page. peer_type and
// peer_id break ties across peers, whose local_id spaces are not comparable, and
// local_id breaks the rest. The keyset is one row comparison against that whole
// tuple, so a page resumes exactly where the previous one stopped.
//
// Each arm carries a limit of its own, so at most 2 * lim rows reach the merge
// and the hydration behind it. That bounds the reply and everything downstream
// of this query — it does not bound the match. The sort key is computed, so
// neither arm has an index that returns rows already ordered and each one
// top-N sorts every row its predicate matches; the posts arm's predicate is the
// membership EXISTS, which the planner may apply either before or after the GIN
// match. Both arms are index-backed rather than sequential, which is the same
// cost the per-channel search accepted, and what bounds an account's total
// spend here is the per-account quota on the RPC, not this statement.
func (q *Queries) SearchGlobalPage(ctx context.Context, arg SearchGlobalPageParams) ([]SearchGlobalPageRow, error) {
	rows, err := q.db.Query(ctx, searchGlobalPage,
		arg.Lim,
		arg.OwnerID,
		arg.Query,
		arg.HasCursor,
		arg.OffsetRate,
		arg.OffsetPeerType,
		arg.OffsetPeerID,
		arg.OffsetID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchGlobalPageRow
	for rows.Next() {
		var i SearchGlobalPageRow
		if err := rows.Scan(
			&i.Rate,
			&i.PeerType,
			&i.PeerID,
			&i.MsgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
