// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_chats.sql

package db

import (
	"context"
)

const acceptSecretChat = `-- name: AcceptSecretChat :one
UPDATE secret_chats
SET state = 'active', g_a_or_b = $1, key_fingerprint = $2
WHERE id = $3 AND participant_id = $4 AND state = 'requested'
RETURNING id, admin_id, participant_id, state, g_a_hash, g_a, g_a_or_b, key_fingerprint, date, random_id
`

type AcceptSecretChatParams struct {
	GAOrB          []byte
	KeyFingerprint *int64
	ID             int32
	ParticipantID  int64
}

// AcceptSecretChat is the whole replay guard: the state and participant
// predicates make a second accept, and an accept by the initiator, match zero
// rows instead of rewriting the fingerprint under a chat the initiator has
// already keyed.
func (q *Queries) AcceptSecretChat(ctx context.Context, arg AcceptSecretChatParams) (SecretChat, error) {
	row := q.db.QueryRow(ctx, acceptSecretChat,
		arg.GAOrB,
		arg.KeyFingerprint,
		arg.ID,
		arg.ParticipantID,
	)
	var i SecretChat
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ParticipantID,
		&i.State,
		&i.GAHash,
		&i.GA,
		&i.GAOrB,
		&i.KeyFingerprint,
		&i.Date,
		&i.RandomID,
	)
	return i, err
}

const bumpQts = `-- name: BumpQts :one
UPDATE update_state SET qts = qts + 1, date = now() WHERE user_id = $1 RETURNING qts
`

// BumpQts atomically increments the recipient's qts. Called in the same
// transaction as InsertEncryptedEvent after the insert confirms this is not a
// dedup. The new qts matches the value InsertEncryptedEvent stored.
func (q *Queries) BumpQts(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, bumpQts, userID)
	var qts int64
	err := row.Scan(&qts)
	return qts, err
}

const countRequestedSecretChats = `-- name: CountRequestedSecretChats :one
SELECT COUNT(*) FROM secret_chats WHERE admin_id = $1 AND state = 'requested'
`

// Outstanding requests the caller has initiated, for the per-account cap. Only
// rows the caller admins are counted, so an inbound request never costs quota.
func (q *Queries) CountRequestedSecretChats(ctx context.Context, adminID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestedSecretChats, adminID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const discardSecretChat = `-- name: DiscardSecretChat :one
UPDATE secret_chats
SET state = 'discarded'
WHERE id = $1 AND state IN ('requested', 'active')
RETURNING id, admin_id, participant_id, state, g_a_hash, g_a, g_a_or_b, key_fingerprint, date, random_id
`

// DiscardSecretChat is idempotent by predicate: a chat already discarded matches
// zero rows, and 'discarded' is terminal.
func (q *Queries) DiscardSecretChat(ctx context.Context, id int32) (SecretChat, error) {
	row := q.db.QueryRow(ctx, discardSecretChat, id)
	var i SecretChat
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ParticipantID,
		&i.State,
		&i.GAHash,
		&i.GA,
		&i.GAOrB,
		&i.KeyFingerprint,
		&i.Date,
		&i.RandomID,
	)
	return i, err
}

const getSecretChatByAdminRandomID = `-- name: GetSecretChatByAdminRandomID :one
SELECT id, admin_id, participant_id, state, g_a_hash, g_a, g_a_or_b, key_fingerprint, date, random_id FROM secret_chats WHERE admin_id = $1 AND random_id = $2 AND random_id != 0 AND state = 'requested'
`

type GetSecretChatByAdminRandomIDParams struct {
	AdminID  int64
	RandomID int64
}

// ponytail: lookup-before-insert dedup; avoids ON CONFLICT and sequence waste.
func (q *Queries) GetSecretChatByAdminRandomID(ctx context.Context, arg GetSecretChatByAdminRandomIDParams) (SecretChat, error) {
	row := q.db.QueryRow(ctx, getSecretChatByAdminRandomID, arg.AdminID, arg.RandomID)
	var i SecretChat
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ParticipantID,
		&i.State,
		&i.GAHash,
		&i.GA,
		&i.GAOrB,
		&i.KeyFingerprint,
		&i.Date,
		&i.RandomID,
	)
	return i, err
}

const getEncryptedEvent = `-- name: GetEncryptedEvent :one
SELECT owner_id, qts, chat_id, random_id, bytes, date FROM encrypted_events WHERE owner_id = $1 AND qts = $2
`

type GetEncryptedEventParams struct {
	OwnerID int64
	Qts     int64
}

// GetEncryptedEvent fetches one event by its (owner_id, qts) primary key.
// Used by the push handler to build updateNewEncryptedMessage after a NOTIFY.
func (q *Queries) GetEncryptedEvent(ctx context.Context, arg GetEncryptedEventParams) (EncryptedEvent, error) {
	row := q.db.QueryRow(ctx, getEncryptedEvent, arg.OwnerID, arg.Qts)
	var i EncryptedEvent
	err := row.Scan(
		&i.OwnerID,
		&i.Qts,
		&i.ChatID,
		&i.RandomID,
		&i.Bytes,
		&i.Date,
	)
	return i, err
}

const getEncryptedEventByRandomID = `-- name: GetEncryptedEventByRandomID :one
SELECT owner_id, qts, chat_id, random_id, bytes, date FROM encrypted_events WHERE owner_id = $1 AND random_id = $2
`

type GetEncryptedEventByRandomIDParams struct {
	OwnerID  int64
	RandomID int64
}

// GetEncryptedEventByRandomID fetches an existing event by dedup key for the
// dedup response path.
func (q *Queries) GetEncryptedEventByRandomID(ctx context.Context, arg GetEncryptedEventByRandomIDParams) (EncryptedEvent, error) {
	row := q.db.QueryRow(ctx, getEncryptedEventByRandomID, arg.OwnerID, arg.RandomID)
	var i EncryptedEvent
	err := row.Scan(
		&i.OwnerID,
		&i.Qts,
		&i.ChatID,
		&i.RandomID,
		&i.Bytes,
		&i.Date,
	)
	return i, err
}

const insertEncryptedEvent = `-- name: InsertEncryptedEvent :one
INSERT INTO encrypted_events (owner_id, qts, chat_id, random_id, bytes, date)
SELECT $1, us.qts + 1, $2, $3, $4, now()
FROM update_state us WHERE us.user_id = $1
ON CONFLICT (owner_id, random_id) DO NOTHING
RETURNING owner_id, qts, chat_id, random_id, bytes, date
`

type InsertEncryptedEventParams struct {
	OwnerID  int64
	ChatID   int32
	RandomID int64
	Bytes    []byte
}

// InsertEncryptedEvent stores one encrypted payload for the recipient. The qts
// is taken from update_state.qts + 1, which matches the value BumpQts will
// write in the same transaction. The advisory lock on the recipient held by the
// caller serialises concurrent sends so the (owner_id, qts) primary key is
// never contended. ON CONFLICT on (owner_id, random_id) is the dedup guard:
// a repeated random_id returns no rows (pgx.ErrNoRows).
func (q *Queries) InsertEncryptedEvent(ctx context.Context, arg InsertEncryptedEventParams) (EncryptedEvent, error) {
	row := q.db.QueryRow(ctx, insertEncryptedEvent,
		arg.OwnerID,
		arg.ChatID,
		arg.RandomID,
		arg.Bytes,
	)
	var i EncryptedEvent
	err := row.Scan(
		&i.OwnerID,
		&i.Qts,
		&i.ChatID,
		&i.RandomID,
		&i.Bytes,
		&i.Date,
	)
	return i, err
}

const insertSecretChat = `-- name: InsertSecretChat :one
INSERT INTO secret_chats (id, admin_id, participant_id, state, g_a_hash, g_a, random_id)
VALUES ($1, $2, $3, 'requested', $4, $5, $6)
RETURNING id, admin_id, participant_id, state, g_a_hash, g_a, g_a_or_b, key_fingerprint, date, random_id
`

type InsertSecretChatParams struct {
	ID            int32
	AdminID       int64
	ParticipantID int64
	GAHash        []byte
	GA            []byte
	RandomID      int64
}

func (q *Queries) InsertSecretChat(ctx context.Context, arg InsertSecretChatParams) (SecretChat, error) {
	row := q.db.QueryRow(ctx, insertSecretChat,
		arg.ID,
		arg.AdminID,
		arg.ParticipantID,
		arg.GAHash,
		arg.GA,
		arg.RandomID,
	)
	var i SecretChat
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ParticipantID,
		&i.State,
		&i.GAHash,
		&i.GA,
		&i.GAOrB,
		&i.KeyFingerprint,
		&i.Date,
		&i.RandomID,
	)
	return i, err
}

const nextSecretChatID = `-- name: NextSecretChatID :one
SELECT nextval('secret_chats_id_seq')::bigint
`

// Server-allocated chat id. Ids are never reused, including by a discarded chat.
func (q *Queries) NextSecretChatID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSecretChatID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const secretChatByID = `-- name: SecretChatByID :one
SELECT id, admin_id, participant_id, state, g_a_hash, g_a, g_a_or_b, key_fingerprint, date, random_id FROM secret_chats WHERE id = $1
`

func (q *Queries) SecretChatByID(ctx context.Context, id int32) (SecretChat, error) {
	row := q.db.QueryRow(ctx, secretChatByID, id)
	var i SecretChat
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ParticipantID,
		&i.State,
		&i.GAHash,
		&i.GA,
		&i.GAOrB,
		&i.KeyFingerprint,
		&i.Date,
		&i.RandomID,
	)
	return i, err
}
