// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_chats.sql

package db

import (
	"context"
)

const acceptSecretChat = `-- name: AcceptSecretChat :one
UPDATE secret_chats
SET state = 'active', g_a_or_b = $1, key_fingerprint = $2
WHERE id = $3 AND participant_id = $4 AND state = 'requested'
RETURNING id, admin_id, participant_id, state, g_a_hash, g_a, g_a_or_b, key_fingerprint, date
`

type AcceptSecretChatParams struct {
	GAOrB          []byte
	KeyFingerprint *int64
	ID             int32
	ParticipantID  int64
}

// AcceptSecretChat is the whole replay guard: the state and participant
// predicates make a second accept, and an accept by the initiator, match zero
// rows instead of rewriting the fingerprint under a chat the initiator has
// already keyed.
func (q *Queries) AcceptSecretChat(ctx context.Context, arg AcceptSecretChatParams) (SecretChat, error) {
	row := q.db.QueryRow(ctx, acceptSecretChat,
		arg.GAOrB,
		arg.KeyFingerprint,
		arg.ID,
		arg.ParticipantID,
	)
	var i SecretChat
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ParticipantID,
		&i.State,
		&i.GAHash,
		&i.GA,
		&i.GAOrB,
		&i.KeyFingerprint,
		&i.Date,
	)
	return i, err
}

const countRequestedSecretChats = `-- name: CountRequestedSecretChats :one
SELECT COUNT(*) FROM secret_chats WHERE admin_id = $1 AND state = 'requested'
`

// Outstanding requests the caller has initiated, for the per-account cap. Only
// rows the caller admins are counted, so an inbound request never costs quota.
func (q *Queries) CountRequestedSecretChats(ctx context.Context, adminID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestedSecretChats, adminID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const discardSecretChat = `-- name: DiscardSecretChat :one
UPDATE secret_chats
SET state = 'discarded'
WHERE id = $1 AND state IN ('requested', 'active')
RETURNING id, admin_id, participant_id, state, g_a_hash, g_a, g_a_or_b, key_fingerprint, date
`

// DiscardSecretChat is idempotent by predicate: a chat already discarded matches
// zero rows, and 'discarded' is terminal.
func (q *Queries) DiscardSecretChat(ctx context.Context, id int32) (SecretChat, error) {
	row := q.db.QueryRow(ctx, discardSecretChat, id)
	var i SecretChat
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ParticipantID,
		&i.State,
		&i.GAHash,
		&i.GA,
		&i.GAOrB,
		&i.KeyFingerprint,
		&i.Date,
	)
	return i, err
}

const insertSecretChat = `-- name: InsertSecretChat :one
INSERT INTO secret_chats (id, admin_id, participant_id, state, g_a_hash, g_a)
VALUES ($1, $2, $3, 'requested', $4, $5)
RETURNING id, admin_id, participant_id, state, g_a_hash, g_a, g_a_or_b, key_fingerprint, date
`

type InsertSecretChatParams struct {
	ID            int32
	AdminID       int64
	ParticipantID int64
	GAHash        []byte
	GA            []byte
}

func (q *Queries) InsertSecretChat(ctx context.Context, arg InsertSecretChatParams) (SecretChat, error) {
	row := q.db.QueryRow(ctx, insertSecretChat,
		arg.ID,
		arg.AdminID,
		arg.ParticipantID,
		arg.GAHash,
		arg.GA,
	)
	var i SecretChat
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ParticipantID,
		&i.State,
		&i.GAHash,
		&i.GA,
		&i.GAOrB,
		&i.KeyFingerprint,
		&i.Date,
	)
	return i, err
}

const nextSecretChatID = `-- name: NextSecretChatID :one
SELECT nextval('secret_chats_id_seq')::bigint
`

// Server-allocated chat id. Ids are never reused, including by a discarded chat.
func (q *Queries) NextSecretChatID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSecretChatID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const secretChatByID = `-- name: SecretChatByID :one
SELECT id, admin_id, participant_id, state, g_a_hash, g_a, g_a_or_b, key_fingerprint, date FROM secret_chats WHERE id = $1
`

func (q *Queries) SecretChatByID(ctx context.Context, id int32) (SecretChat, error) {
	row := q.db.QueryRow(ctx, secretChatByID, id)
	var i SecretChat
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ParticipantID,
		&i.State,
		&i.GAHash,
		&i.GA,
		&i.GAOrB,
		&i.KeyFingerprint,
		&i.Date,
	)
	return i, err
}
