// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: send_code_ip.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredSendCodeIPPhones = `-- name: DeleteExpiredSendCodeIPPhones :exec
DELETE FROM send_code_ip_phones
WHERE ip_key = $1
  AND expires_at <= now()
`

// Prune one key's expired phone rows before they are counted, so retention is
// the limit window rather than whatever the periodic sweep last reached.
func (q *Queries) DeleteExpiredSendCodeIPPhones(ctx context.Context, ipKey netip.Prefix) error {
	_, err := q.db.Exec(ctx, deleteExpiredSendCodeIPPhones, ipKey)
	return err
}

const getSendCodeIPCallExpiry = `-- name: GetSendCodeIPCallExpiry :one
SELECT expires_at
FROM send_code_ip_calls
WHERE ip_key = $1
`

// Read the expiry deadline of a key's current window, for the wait a denied
// call is told to observe.
func (q *Queries) GetSendCodeIPCallExpiry(ctx context.Context, ipKey netip.Prefix) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getSendCodeIPCallExpiry, ipKey)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getSendCodeIPPhoneNextExpiry = `-- name: GetSendCodeIPPhoneNextExpiry :one
SELECT expires_at
FROM send_code_ip_phones
WHERE ip_key = $1
ORDER BY expires_at
LIMIT 1
`

// The deadline at which a key's oldest phone row frees a slot, which is the
// wait a key denied on the distinct-number quota is told to observe.
func (q *Queries) GetSendCodeIPPhoneNextExpiry(ctx context.Context, ipKey netip.Prefix) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getSendCodeIPPhoneNextExpiry, ipKey)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getSendCodeIPPhoneUsage = `-- name: GetSendCodeIPPhoneUsage :one
SELECT
    count(*)::INT AS used,
    coalesce(bool_or(phone = $2), FALSE)::BOOLEAN AS counted
FROM send_code_ip_phones
WHERE ip_key = $1
`

type GetSendCodeIPPhoneUsageParams struct {
	IpKey netip.Prefix
	Phone string
}

type GetSendCodeIPPhoneUsageRow struct {
	Used    int32
	Counted bool
}

// Report how many distinct phone numbers a key currently holds, and whether the
// one being requested is already among them. A number the key has already been
// charged for costs nothing to repeat; a new one needs a free slot. Caller must
// have pruned first, so every row counted here is still inside its window.
func (q *Queries) GetSendCodeIPPhoneUsage(ctx context.Context, arg GetSendCodeIPPhoneUsageParams) (GetSendCodeIPPhoneUsageRow, error) {
	row := q.db.QueryRow(ctx, getSendCodeIPPhoneUsage, arg.IpKey, arg.Phone)
	var i GetSendCodeIPPhoneUsageRow
	err := row.Scan(&i.Used, &i.Counted)
	return i, err
}

const insertSendCodeIPPhone = `-- name: InsertSendCodeIPPhone :exec
INSERT INTO send_code_ip_phones (ip_key, phone, expires_at)
VALUES ($1, $2, now() + $3::INTERVAL)
ON CONFLICT (ip_key, phone) DO NOTHING
`

type InsertSendCodeIPPhoneParams struct {
	IpKey   netip.Prefix
	Phone   string
	Column3 pgtype.Interval
}

// Charge one distinct phone number to a key. Only called once the usage read
// above has shown the key has a free slot, which is what bounds rows per key by
// the quota itself rather than by request count.
func (q *Queries) InsertSendCodeIPPhone(ctx context.Context, arg InsertSendCodeIPPhoneParams) error {
	_, err := q.db.Exec(ctx, insertSendCodeIPPhone, arg.IpKey, arg.Phone, arg.Column3)
	return err
}

const sweepExpiredSendCodeIPCalls = `-- name: SweepExpiredSendCodeIPCalls :execrows
DELETE FROM send_code_ip_calls
WHERE expires_at <= now()
`

// Delete counter rows whose window has closed. The deadline is on the row, so
// the sweep does not need to know the window duration.
func (q *Queries) SweepExpiredSendCodeIPCalls(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredSendCodeIPCalls)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepExpiredSendCodeIPPhones = `-- name: SweepExpiredSendCodeIPPhones :execrows
DELETE FROM send_code_ip_phones
WHERE expires_at <= now()
`

// Delete phone rows past their retention deadline. Keys that stay active prune
// their own rows on write; this is what clears the ones that go quiet.
func (q *Queries) SweepExpiredSendCodeIPPhones(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredSendCodeIPPhones)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryConsumeSendCodeIPCall = `-- name: TryConsumeSendCodeIPCall :one
INSERT INTO send_code_ip_calls (ip_key, token_count, window_start, expires_at)
VALUES ($1, 1, now(), now() + $2::INTERVAL)
ON CONFLICT (ip_key) DO UPDATE SET
    token_count = CASE
        WHEN send_code_ip_calls.expires_at <= now() THEN 1
        ELSE send_code_ip_calls.token_count + 1
    END,
    window_start = CASE
        WHEN send_code_ip_calls.expires_at <= now() THEN now()
        ELSE send_code_ip_calls.window_start
    END,
    expires_at = CASE
        WHEN send_code_ip_calls.expires_at <= now() THEN now() + $2::INTERVAL
        ELSE send_code_ip_calls.expires_at
    END
WHERE send_code_ip_calls.expires_at <= now()
   OR send_code_ip_calls.token_count < $3
RETURNING token_count, expires_at
`

type TryConsumeSendCodeIPCallParams struct {
	IpKey      netip.Prefix
	Column2    pgtype.Interval
	TokenCount int32
}

type TryConsumeSendCodeIPCallRow struct {
	TokenCount int32
	ExpiresAt  pgtype.Timestamptz
}

// Attempt to consume one sendCode token for an IP key.
//
// INSERT seeds a new counter; ON CONFLICT fires the DO UPDATE:
//   - Window closed: reset count=1, window_start=now, expires_at=now+window.
//   - Window open, under limit: bump count.
//   - Window open, at limit: the WHERE clause prevents the UPDATE entirely.
//
// Whether the window is closed is read from expires_at, the deadline stored
// when the window opened, and never recomputed as window_start + the current
// config. That is the one boundary the sweep can also see, and the two must
// agree: derive it from the live config instead and changing the config splits
// them, so the sweep collects a row the limiter is still counting against and
// the key silently gets a fresh budget. The consequence is deliberate — a
// config change takes effect at the next window rather than mid-flight, in
// either direction, and never grants a key more than the window it opened with.
//
// Returns one row when the call is allowed, and pgx.ErrNoRows when it is not.
// One row per key per window, never one per call: this is an unauthenticated
// path and the table must not grow with request count.
func (q *Queries) TryConsumeSendCodeIPCall(ctx context.Context, arg TryConsumeSendCodeIPCallParams) (TryConsumeSendCodeIPCallRow, error) {
	row := q.db.QueryRow(ctx, tryConsumeSendCodeIPCall, arg.IpKey, arg.Column2, arg.TokenCount)
	var i TryConsumeSendCodeIPCallRow
	err := row.Scan(&i.TokenCount, &i.ExpiresAt)
	return i, err
}
