// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sign_in_fail.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const chargeSignInFailCall = `-- name: ChargeSignInFailCall :one
INSERT INTO sign_in_fail_calls (ip_key, token_count, window_start, expires_at)
VALUES ($1, 1, now(), now() + $2::INTERVAL)
ON CONFLICT (ip_key) DO UPDATE SET
    token_count = CASE
        WHEN sign_in_fail_calls.expires_at <= now() THEN 1
        ELSE sign_in_fail_calls.token_count + 1
    END,
    window_start = CASE
        WHEN sign_in_fail_calls.expires_at <= now() THEN now()
        ELSE sign_in_fail_calls.window_start
    END,
    expires_at = CASE
        WHEN sign_in_fail_calls.expires_at <= now() THEN now() + $2::INTERVAL
        ELSE sign_in_fail_calls.expires_at
    END
WHERE sign_in_fail_calls.expires_at <= now()
   OR sign_in_fail_calls.token_count < $3
RETURNING token_count, expires_at
`

type ChargeSignInFailCallParams struct {
	IpKey      netip.Prefix
	Column2    pgtype.Interval
	TokenCount int32
}

type ChargeSignInFailCallRow struct {
	TokenCount int32
	ExpiresAt  pgtype.Timestamptz
}

// Conditional charge: add one token to the counter only if the budget is not
// exhausted. Called before VerifyCode to reserve a slot. Returns pgx.ErrNoRows
// when the window is open and at the limit — the racing request that already
// consumed the last token wins, and the others get an error the handler fails
// closed on.
func (q *Queries) ChargeSignInFailCall(ctx context.Context, arg ChargeSignInFailCallParams) (ChargeSignInFailCallRow, error) {
	row := q.db.QueryRow(ctx, chargeSignInFailCall, arg.IpKey, arg.Column2, arg.TokenCount)
	var i ChargeSignInFailCallRow
	err := row.Scan(&i.TokenCount, &i.ExpiresAt)
	return i, err
}

const getSignInFailCallExpiry = `-- name: GetSignInFailCallExpiry :one
SELECT expires_at
FROM sign_in_fail_calls
WHERE ip_key = $1
`

// Read the expiry deadline of a key's current window, for the wait a denied
// attempt is told to observe.
func (q *Queries) GetSignInFailCallExpiry(ctx context.Context, ipKey netip.Prefix) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getSignInFailCallExpiry, ipKey)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const refundSignInFailCall = `-- name: RefundSignInFailCall :exec
UPDATE sign_in_fail_calls
SET token_count = GREATEST(token_count - 1, 0)
WHERE ip_key = $1 AND expires_at > now()
`

// Return a reserved slot to the counter. Called after a successful verification
// or an internal error (no verification happened). Decrements token_count by 1,
// floored at 0. Only applies to active windows.
func (q *Queries) RefundSignInFailCall(ctx context.Context, ipKey netip.Prefix) error {
	_, err := q.db.Exec(ctx, refundSignInFailCall, ipKey)
	return err
}

const sweepExpiredSignInFailCalls = `-- name: SweepExpiredSignInFailCalls :execrows
DELETE FROM sign_in_fail_calls
WHERE expires_at <= now()
`

// Delete counter rows whose window has closed.
func (q *Queries) SweepExpiredSignInFailCalls(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredSignInFailCalls)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
