// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sign_in_fail.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSignInFailCallExpiry = `-- name: GetSignInFailCallExpiry :one
SELECT expires_at
FROM sign_in_fail_calls
WHERE ip_key = $1
`

// Read the expiry deadline of a key's current window, for the wait a denied
// attempt is told to observe.
func (q *Queries) GetSignInFailCallExpiry(ctx context.Context, ipKey netip.Prefix) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getSignInFailCallExpiry, ipKey)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const sweepExpiredSignInFailCalls = `-- name: SweepExpiredSignInFailCalls :execrows
DELETE FROM sign_in_fail_calls
WHERE expires_at <= now()
`

// Delete counter rows whose window has closed.
func (q *Queries) SweepExpiredSignInFailCalls(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredSignInFailCalls)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryConsumeSignInFailCall = `-- name: TryConsumeSignInFailCall :one
INSERT INTO sign_in_fail_calls (ip_key, token_count, window_start, expires_at)
VALUES ($1, 1, now(), now() + $2::INTERVAL)
ON CONFLICT (ip_key) DO UPDATE SET
    token_count = CASE
        WHEN sign_in_fail_calls.expires_at <= now() THEN 1
        ELSE sign_in_fail_calls.token_count + 1
    END,
    window_start = CASE
        WHEN sign_in_fail_calls.expires_at <= now() THEN now()
        ELSE sign_in_fail_calls.window_start
    END,
    expires_at = CASE
        WHEN sign_in_fail_calls.expires_at <= now() THEN now() + $2::INTERVAL
        ELSE sign_in_fail_calls.expires_at
    END
WHERE sign_in_fail_calls.expires_at <= now()
   OR sign_in_fail_calls.token_count < $3
RETURNING token_count, expires_at
`

type TryConsumeSignInFailCallParams struct {
	IpKey      netip.Prefix
	Column2    pgtype.Interval
	TokenCount int32
}

type TryConsumeSignInFailCallRow struct {
	TokenCount int32
	ExpiresAt  pgtype.Timestamptz
}

// Attempt to consume one signIn-fail token for an IP key.
//
// Same upsert pattern as send_code_ip_calls: one row per key per window,
// token_count reset and bumped. Returns one row when allowed, pgx.ErrNoRows
// when the window is open and at the limit.
func (q *Queries) TryConsumeSignInFailCall(ctx context.Context, arg TryConsumeSignInFailCallParams) (TryConsumeSignInFailCallRow, error) {
	row := q.db.QueryRow(ctx, tryConsumeSignInFailCall, arg.IpKey, arg.Column2, arg.TokenCount)
	var i TryConsumeSignInFailCallRow
	err := row.Scan(&i.TokenCount, &i.ExpiresAt)
	return i, err
}
