// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimExpiredUploadParts = `-- name: ClaimExpiredUploadParts :many

SELECT old.user_id, old.file_id, old.part_index, old.blob_key
FROM upload_parts old
WHERE old.date < $1
ORDER BY old.date
LIMIT $2::int
FOR UPDATE SKIP LOCKED
`

type ClaimExpiredUploadPartsParams struct {
	Date pgtype.Timestamptz
	Lim  int32
}

type ClaimExpiredUploadPartsRow struct {
	UserID    int64
	FileID    int64
	PartIndex int32
	BlobKey   string
}

// There is deliberately no delete over a whole upload. DeleteUploadPartByKey
// below is the only statement that removes a parts row, so a row can only be
// retired by naming it and the key whose bytes were deleted for it. A
// convenience delete over (user_id, file_id) is what the assembly cleanup used
// to run, and it dropped rows whose bytes it had never touched.
// ClaimExpiredUploadParts takes at most one batch of expired parts, oldest
// first, returning each row's primary key and the blob key it names. The bound
// is the point: unbounded, this is one statement over every account's expired
// rows, holding row locks and writing WAL in proportion to whatever
// accumulated while the sweep was down. The caller repeats it until a pass
// comes back short.
//
// It partitions nothing between replicas, and must not be read as if it did.
// The caller runs it in autocommit, so FOR UPDATE SKIP LOCKED holds its row
// locks only to the end of the statement: two replicas sweeping at once can
// and do take the same rows. That is safe rather than merely tolerated —
// deleting an object twice is a no-op and the conditional row delete below
// matches at most once — and it is why no durable claim column exists here.
// SKIP LOCKED stays because it keeps a pass from blocking behind another
// replica's in-flight statement.
func (q *Queries) ClaimExpiredUploadParts(ctx context.Context, arg ClaimExpiredUploadPartsParams) ([]ClaimExpiredUploadPartsRow, error) {
	rows, err := q.db.Query(ctx, claimExpiredUploadParts, arg.Date, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimExpiredUploadPartsRow
	for rows.Next() {
		var i ClaimExpiredUploadPartsRow
		if err := rows.Scan(
			&i.UserID,
			&i.FileID,
			&i.PartIndex,
			&i.BlobKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUploadPartByKey = `-- name: DeleteUploadPartByKey :execrows
DELETE FROM upload_parts
WHERE user_id = $1 AND file_id = $2 AND part_index = $3 AND blob_key = $4
`

type DeleteUploadPartByKeyParams struct {
	UserID    int64
	FileID    int64
	PartIndex int32
	BlobKey   string
}

// DeleteUploadPartByKey drops one claimed row, and only if it still names the
// key whose bytes the sweep deleted. Both halves matter. The primary key makes
// it one row: the rows a deploy leaves behind all carry the same empty
// blob_key, and a delete keyed on blob_key alone would take every one of them
// on the first claimed key, which is the per-batch bound gone in exactly the
// case it is needed. The blob_key condition makes it conditional: a re-save
// that committed in the window between the claim and the byte delete has
// renamed the row, and its row and its new object both survive.
func (q *Queries) DeleteUploadPartByKey(ctx context.Context, arg DeleteUploadPartByKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUploadPartByKey,
		arg.UserID,
		arg.FileID,
		arg.PartIndex,
		arg.BlobKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fileOutstandingBytes = `-- name: FileOutstandingBytes :one
SELECT coalesce(sum(size), 0)::bigint FROM upload_parts
WHERE user_id = $1 AND file_id = $2
`

type FileOutstandingBytesParams struct {
	UserID int64
	FileID int64
}

// FileOutstandingBytes sums the recorded sizes. The caps aggregate over rows,
// so a retry is still not billed twice: there is no counter to increment,
// only a SUM over rows the upsert has already deduplicated.
func (q *Queries) FileOutstandingBytes(ctx context.Context, arg FileOutstandingBytesParams) (int64, error) {
	row := q.db.QueryRow(ctx, fileOutstandingBytes, arg.UserID, arg.FileID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const livePartBlobKeys = `-- name: LivePartBlobKeys :many
SELECT blob_key FROM upload_parts
WHERE blob_key <> ''
ORDER BY user_id, file_id, part_index
LIMIT $2::int OFFSET $1::int
`

type LivePartBlobKeysParams struct {
	Off int32
	Lim int32
}

// LivePartBlobKeys returns every blob key a parts row still names. The
// orphan pass uses this to tell an object no row points at (reclaimable) from
// one a live row still does (never touch). A single bounded statement; the
// caller batches with OFFSET when the row count is large.
func (q *Queries) LivePartBlobKeys(ctx context.Context, arg LivePartBlobKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, livePartBlobKeys, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var blob_key string
		if err := rows.Scan(&blob_key); err != nil {
			return nil, err
		}
		items = append(items, blob_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uploadPartKey = `-- name: UploadPartKey :one
SELECT blob_key, size FROM upload_parts WHERE user_id = $1 AND file_id = $2 AND part_index = $3
`

type UploadPartKeyParams struct {
	UserID    int64
	FileID    int64
	PartIndex int32
}

type UploadPartKeyRow struct {
	BlobKey string
	Size    int64
}

// UploadPartKey returns one part's recorded blob key and size. The key is
// what the bytes are read back from; the size is what assembly reconciles
// the read against.
func (q *Queries) UploadPartKey(ctx context.Context, arg UploadPartKeyParams) (UploadPartKeyRow, error) {
	row := q.db.QueryRow(ctx, uploadPartKey, arg.UserID, arg.FileID, arg.PartIndex)
	var i UploadPartKeyRow
	err := row.Scan(&i.BlobKey, &i.Size)
	return i, err
}

const uploadPartRefs = `-- name: UploadPartRefs :many
SELECT part_index, blob_key, size FROM upload_parts
WHERE user_id = $1 AND file_id = $2
ORDER BY part_index
`

type UploadPartRefsParams struct {
	UserID int64
	FileID int64
}

type UploadPartRefsRow struct {
	PartIndex int32
	BlobKey   string
	Size      int64
}

// UploadPartRefs lists an upload's parts in index order, each with the key its
// bytes are read back from and the size that read is reconciled against. It is
// the whole of what assembly needs from Postgres: one statement instead of a
// key lookup per part on the validation pass and a second one per part on the
// read pass. The assembly cleanup takes its keys from here too, so the bytes
// go before the rows.
func (q *Queries) UploadPartRefs(ctx context.Context, arg UploadPartRefsParams) ([]UploadPartRefsRow, error) {
	rows, err := q.db.Query(ctx, uploadPartRefs, arg.UserID, arg.FileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadPartRefsRow
	for rows.Next() {
		var i UploadPartRefsRow
		if err := rows.Scan(&i.PartIndex, &i.BlobKey, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uploadPartsSummary = `-- name: UploadPartsSummary :one
SELECT count(*)::bigint AS parts,
       coalesce(max(part_index), -1)::int AS max_index,
       coalesce(sum(size), 0)::bigint AS total_bytes
FROM upload_parts WHERE user_id = $1 AND file_id = $2
`

type UploadPartsSummaryParams struct {
	UserID int64
	FileID int64
}

type UploadPartsSummaryRow struct {
	Parts      int64
	MaxIndex   int32
	TotalBytes int64
}

// UploadPartsSummary is what assembly checks contiguity with: part indexes are
// distinct by the primary key and non-negative because partIndexOf rejects a
// negative index, so n = total and max = total-1 together prove the set is
// exactly {0 .. total-1} with no gaps.
func (q *Queries) UploadPartsSummary(ctx context.Context, arg UploadPartsSummaryParams) (UploadPartsSummaryRow, error) {
	row := q.db.QueryRow(ctx, uploadPartsSummary, arg.UserID, arg.FileID)
	var i UploadPartsSummaryRow
	err := row.Scan(&i.Parts, &i.MaxIndex, &i.TotalBytes)
	return i, err
}

const upsertUploadPart = `-- name: UpsertUploadPart :one
WITH superseded AS (
    SELECT prev.blob_key FROM upload_parts prev
    WHERE prev.user_id = $1 AND prev.file_id = $2 AND prev.part_index = $3
), upserted AS (
    INSERT INTO upload_parts (user_id, file_id, part_index, size, blob_key)
    VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT (user_id, file_id, part_index)
    DO UPDATE SET size = excluded.size,
                  blob_key = excluded.blob_key
    RETURNING 1
)
SELECT coalesce((SELECT blob_key FROM superseded), '')::text AS superseded_key
`

type UpsertUploadPartParams struct {
	UserID    int64
	FileID    int64
	PartIndex int32
	Size      int64
	BlobKey   string
}

// UpsertUploadPart writes one part's accounting row. The bytes live in the
// blob store under blob_key; the row names the key and the server-measured
// size, and nothing in the row is client-declared.
//
// Re-saving the same part is legal — a client retries a failed part — so this
// is an upsert, and the caller re-reads the sums afterwards rather than
// tracking a delta.
//
// The conflict clause is the size rule: the recorded size describes the object
// the row currently names, and nothing else. Every save draws a fresh key, so
// the size and the key move together — a row can never claim a size the object
// it names does not have. Holding a superseded larger size instead would
// describe an object that is about to be deleted, and the fail-closed read at
// assembly would then reject a perfectly well-formed upload.
//
// The superseded key is what this returns, empty when the part is new. The
// object it names is unreachable from any row the moment this commits, so the
// caller deletes it: without that, a client looping saveFilePart on one part
// grows stored bytes without bound while the row-based caps stay flat.
//
// The pre-conflict read is a plain CTE, so it runs against the statement's
// snapshot and sees the row as it was before the upsert. The INSERT is a
// data-modifying CTE and executes exactly once whether or not the final SELECT
// references it.
//
// date is deliberately NOT refreshed on conflict: it is what the TTL sweep
// measures from, so a re-save that moved it would let an account hold an
// outstanding set alive forever by touching each part every TTL/2.
func (q *Queries) UpsertUploadPart(ctx context.Context, arg UpsertUploadPartParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertUploadPart,
		arg.UserID,
		arg.FileID,
		arg.PartIndex,
		arg.Size,
		arg.BlobKey,
	)
	var superseded_key string
	err := row.Scan(&superseded_key)
	return superseded_key, err
}

const userOutstanding = `-- name: UserOutstanding :one
SELECT count(*)::bigint AS parts,
       coalesce(sum(size), 0)::bigint AS total_bytes
FROM upload_parts WHERE user_id = $1
`

type UserOutstandingRow struct {
	Parts      int64
	TotalBytes int64
}

func (q *Queries) UserOutstanding(ctx context.Context, userID int64) (UserOutstandingRow, error) {
	row := q.db.QueryRow(ctx, userOutstanding, userID)
	var i UserOutstandingRow
	err := row.Scan(&i.Parts, &i.TotalBytes)
	return i, err
}
