// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredUploadParts = `-- name: DeleteExpiredUploadParts :execrows
DELETE FROM upload_parts WHERE date < $1
`

func (q *Queries) DeleteExpiredUploadParts(ctx context.Context, date pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUploadParts, date)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUploadParts = `-- name: DeleteUploadParts :execrows
DELETE FROM upload_parts WHERE user_id = $1 AND file_id = $2
`

type DeleteUploadPartsParams struct {
	UserID int64
	FileID int64
}

func (q *Queries) DeleteUploadParts(ctx context.Context, arg DeleteUploadPartsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUploadParts, arg.UserID, arg.FileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fileOutstandingBytes = `-- name: FileOutstandingBytes :one
SELECT coalesce(sum(length(payload)), 0)::bigint FROM upload_parts
WHERE user_id = $1 AND file_id = $2
`

type FileOutstandingBytesParams struct {
	UserID int64
	FileID int64
}

func (q *Queries) FileOutstandingBytes(ctx context.Context, arg FileOutstandingBytesParams) (int64, error) {
	row := q.db.QueryRow(ctx, fileOutstandingBytes, arg.UserID, arg.FileID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const uploadPartPayload = `-- name: UploadPartPayload :one
SELECT payload FROM upload_parts WHERE user_id = $1 AND file_id = $2 AND part_index = $3
`

type UploadPartPayloadParams struct {
	UserID    int64
	FileID    int64
	PartIndex int32
}

func (q *Queries) UploadPartPayload(ctx context.Context, arg UploadPartPayloadParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, uploadPartPayload, arg.UserID, arg.FileID, arg.PartIndex)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const uploadPartsSummary = `-- name: UploadPartsSummary :one
SELECT count(*)::bigint AS parts,
       coalesce(max(part_index), -1)::int AS max_index,
       coalesce(sum(length(payload)), 0)::bigint AS total_bytes
FROM upload_parts WHERE user_id = $1 AND file_id = $2
`

type UploadPartsSummaryParams struct {
	UserID int64
	FileID int64
}

type UploadPartsSummaryRow struct {
	Parts      int64
	MaxIndex   int32
	TotalBytes int64
}

// UploadPartsSummary is what assembly checks contiguity with: part indexes are
// distinct by the primary key and non-negative because partIndexOf rejects a
// negative index, so n = total and max = total-1 together prove the set is
// exactly {0 .. total-1} with no gaps.
func (q *Queries) UploadPartsSummary(ctx context.Context, arg UploadPartsSummaryParams) (UploadPartsSummaryRow, error) {
	row := q.db.QueryRow(ctx, uploadPartsSummary, arg.UserID, arg.FileID)
	var i UploadPartsSummaryRow
	err := row.Scan(&i.Parts, &i.MaxIndex, &i.TotalBytes)
	return i, err
}

const upsertUploadPart = `-- name: UpsertUploadPart :exec
INSERT INTO upload_parts (user_id, file_id, part_index, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, file_id, part_index)
DO UPDATE SET payload = excluded.payload, date = now()
`

type UpsertUploadPartParams struct {
	UserID    int64
	FileID    int64
	PartIndex int32
	Payload   []byte
}

// UpsertUploadPart writes one part of an in-flight upload. Re-saving the same
// part is legal — a client retries a failed part — so this is an upsert, and
// the caller re-reads the sums afterwards rather than tracking a delta.
func (q *Queries) UpsertUploadPart(ctx context.Context, arg UpsertUploadPartParams) error {
	_, err := q.db.Exec(ctx, upsertUploadPart,
		arg.UserID,
		arg.FileID,
		arg.PartIndex,
		arg.Payload,
	)
	return err
}

const userOutstanding = `-- name: UserOutstanding :one
SELECT count(*)::bigint AS parts,
       coalesce(sum(length(payload)), 0)::bigint AS total_bytes
FROM upload_parts WHERE user_id = $1
`

type UserOutstandingRow struct {
	Parts      int64
	TotalBytes int64
}

func (q *Queries) UserOutstanding(ctx context.Context, userID int64) (UserOutstandingRow, error) {
	row := q.db.QueryRow(ctx, userOutstanding, userID)
	var i UserOutstandingRow
	err := row.Scan(&i.Parts, &i.TotalBytes)
	return i, err
}
