// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usernames.sql

package db

import (
	"context"
)

const claimUsername = `-- name: ClaimUsername :one
INSERT INTO usernames (handle, owner_type, owner_id) VALUES (lower($1), $2, $3)
RETURNING handle, owner_type, owner_id
`

type ClaimUsernameParams struct {
	Lower     string
	OwnerType string
	OwnerID   int64
}

func (q *Queries) ClaimUsername(ctx context.Context, arg ClaimUsernameParams) (Username, error) {
	row := q.db.QueryRow(ctx, claimUsername, arg.Lower, arg.OwnerType, arg.OwnerID)
	var i Username
	err := row.Scan(&i.Handle, &i.OwnerType, &i.OwnerID)
	return i, err
}

const getChannelByUsername = `-- name: GetChannelByUsername :one
SELECT c.id, c.title, c.about, c.creator_id, c.megagroup, c.version, c.date, c.pinned_message_id, c.username FROM channels c
JOIN usernames un ON un.owner_type = 'channel' AND un.owner_id = c.id
WHERE un.handle = lower($1)
`

func (q *Queries) GetChannelByUsername(ctx context.Context, lower string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByUsername, lower)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.Username,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT u.id, u.phone, u.first_name, u.last_name, u.created_at, u.is_online, u.last_seen_at, u.username FROM users u
JOIN usernames un ON un.owner_type = 'user' AND un.owner_id = u.id
WHERE un.handle = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.Username,
	)
	return i, err
}

const getUsernameByHandle = `-- name: GetUsernameByHandle :one
SELECT handle, owner_type, owner_id FROM usernames WHERE handle = lower($1)
`

func (q *Queries) GetUsernameByHandle(ctx context.Context, lower string) (Username, error) {
	row := q.db.QueryRow(ctx, getUsernameByHandle, lower)
	var i Username
	err := row.Scan(&i.Handle, &i.OwnerType, &i.OwnerID)
	return i, err
}

const releaseUsername = `-- name: ReleaseUsername :execrows
DELETE FROM usernames WHERE handle = lower($1) AND owner_type = $2 AND owner_id = $3
`

type ReleaseUsernameParams struct {
	Lower     string
	OwnerType string
	OwnerID   int64
}

func (q *Queries) ReleaseUsername(ctx context.Context, arg ReleaseUsernameParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseUsername, arg.Lower, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
