// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: username_lookups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsernameLookups = `-- name: CountUsernameLookups :one
SELECT COUNT(DISTINCT handle)
FROM username_lookups
WHERE caller_id = $1
  AND looked_up_at >= $2
`

type CountUsernameLookupsParams struct {
	CallerID   int64
	LookedUpAt pgtype.Timestamptz
}

// Count distinct handles looked up by caller_id since the cutoff.
func (q *Queries) CountUsernameLookups(ctx context.Context, arg CountUsernameLookupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsernameLookups, arg.CallerID, arg.LookedUpAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredUsernameLookups = `-- name: DeleteExpiredUsernameLookups :exec
DELETE FROM username_lookups
WHERE caller_id = $1
  AND looked_up_at < $2
`

type DeleteExpiredUsernameLookupsParams struct {
	CallerID   int64
	LookedUpAt pgtype.Timestamptz
}

// Remove lookups older than the window for a specific caller.
func (q *Queries) DeleteExpiredUsernameLookups(ctx context.Context, arg DeleteExpiredUsernameLookupsParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredUsernameLookups, arg.CallerID, arg.LookedUpAt)
	return err
}

const insertUsernameLookup = `-- name: InsertUsernameLookup :exec
INSERT INTO username_lookups (caller_id, handle, looked_up_at)
VALUES ($1, $2, $3)
`

type InsertUsernameLookupParams struct {
	CallerID   int64
	Handle     string
	LookedUpAt pgtype.Timestamptz
}

// Record a lookup attempt. caller_id and handle are the normalized values.
// looked_up_at is passed from Go (time.Now() after the advisory lock) so the
// burst window is measured against wall-clock time, not transaction-start time.
func (q *Queries) InsertUsernameLookup(ctx context.Context, arg InsertUsernameLookupParams) error {
	_, err := q.db.Exec(ctx, insertUsernameLookup, arg.CallerID, arg.Handle, arg.LookedUpAt)
	return err
}
