// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: username_changes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsernameChanges = `-- name: CountUsernameChanges :one
SELECT COUNT(*)
FROM username_changes
WHERE user_id = $1
  AND changed_at >= $2
`

type CountUsernameChangesParams struct {
	UserID    int64
	ChangedAt pgtype.Timestamptz
}

// Count changes by user_id since the cutoff.
func (q *Queries) CountUsernameChanges(ctx context.Context, arg CountUsernameChangesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsernameChanges, arg.UserID, arg.ChangedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredUsernameChanges = `-- name: DeleteExpiredUsernameChanges :exec
DELETE FROM username_changes
WHERE user_id = $1
  AND changed_at < $2
`

type DeleteExpiredUsernameChangesParams struct {
	UserID    int64
	ChangedAt pgtype.Timestamptz
}

// Remove changes older than the window for a specific user.
func (q *Queries) DeleteExpiredUsernameChanges(ctx context.Context, arg DeleteExpiredUsernameChangesParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredUsernameChanges, arg.UserID, arg.ChangedAt)
	return err
}

const insertUsernameChange = `-- name: InsertUsernameChange :exec
INSERT INTO username_changes (user_id, changed_at)
VALUES ($1, now())
`

// Record a username change attempt.
func (q *Queries) InsertUsernameChange(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, insertUsernameChange, userID)
	return err
}
