// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

WITH upserted AS (
    INSERT INTO users (phone) VALUES ($1)
    ON CONFLICT (phone) DO UPDATE SET phone = EXCLUDED.phone
    RETURNING id, phone, first_name, last_name, created_at, is_online, last_seen_at
)
SELECT u.id, u.phone, u.first_name, u.last_name, u.created_at, u.is_online, u.last_seen_at,
       un.handle AS username
FROM upserted u
LEFT JOIN usernames un ON un.owner_type = 'user' AND un.owner_id = u.id
`

type CreateUserRow struct {
	ID         int64
	Phone      string
	FirstName  string
	LastName   string
	CreatedAt  pgtype.Timestamptz
	IsOnline   bool
	LastSeenAt pgtype.Timestamptz
	Username   *string
}

// Every query that loads a user reads the handle from the usernames row, never
// from the denormalized users.username column. The two are written in one
// transaction today, but only the usernames row is authoritative: it is what
// admits an account to resolveUsername, and a writer that released a handle
// without clearing the copy must not leave any RPC still reporting it. The join
// is a nested loop on usernames_owner_idx (owner_type, owner_id), 0.11 ms for a
// user lookup against 200k handles, so the hot per-peer read pays an index
// probe rather than the copy's zero.
func (q *Queries) CreateUser(ctx context.Context, phone string) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, phone)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.Username,
	)
	return i, err
}

const searchContactsByName = `-- name: SearchContactsByName :many
SELECT u.id, u.phone, u.first_name, u.last_name, u.created_at, u.is_online, u.last_seen_at,
       un.handle AS username
FROM users u
LEFT JOIN usernames un ON un.owner_type = 'user' AND un.owner_id = u.id
WHERE u.name_tsv @@ plainto_tsquery('simple', $1)
  AND EXISTS (
      SELECT 1 FROM dialogs d
      WHERE d.owner_id = $2::bigint
        AND d.peer_id = u.id
        AND d.peer_type = 1
  )
ORDER BY u.id
LIMIT $3::int
`

type SearchContactsByNameParams struct {
	Query   string
	OwnerID int64
	Lim     int32
}

type SearchContactsByNameRow struct {
	ID         int64
	Phone      string
	FirstName  string
	LastName   string
	CreatedAt  pgtype.Timestamptz
	IsOnline   bool
	LastSeenAt pgtype.Timestamptz
	Username   *string
}

// Search users by name within the caller's existing dialogs.
// Only users with whom the caller has exchanged messages (has a dialog row) are returned.
// The single owner_id arm is sufficient: sending a message writes two dialog rows
// in one transaction (caller-owned and peer-owned), so the caller always has a
// row where owner_id = caller. The second arm (peer_id = caller) was removed
// because it authorizes off rows the caller does not own — a future history-deletion
// path could delete the peer-owned row without deleting the caller-owned one,
// making the second arm incorrectly permissive. It also costs ~618 ms vs 0.10 ms
// (seq-scan vs index-only) at 200k users.
//
// ORDER BY u.id is what makes the page deterministic. MyResults unions this arm
// with the caller's matching channels under ONE limit budget, so rows past the
// budget are dropped; without a total order the set that survives truncation is
// whatever the plan happened to emit, and two identical searches disagree. It
// is the same order the channel arms use.
func (q *Queries) SearchContactsByName(ctx context.Context, arg SearchContactsByNameParams) ([]SearchContactsByNameRow, error) {
	rows, err := q.db.Query(ctx, searchContactsByName, arg.Query, arg.OwnerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchContactsByNameRow
	for rows.Next() {
		var i SearchContactsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.IsOnline,
			&i.LastSeenAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStatus = `-- name: SetUserStatus :execrows
UPDATE users SET is_online = $2, last_seen_at = now() WHERE id = $1
`

type SetUserStatusParams struct {
	ID       int64
	IsOnline bool
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserStatus, arg.ID, arg.IsOnline)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUsername = `-- name: SetUsername :execrows
UPDATE users SET username = $2 WHERE id = $1
`

type SetUsernameParams struct {
	ID       int64
	Username *string
}

func (q *Queries) SetUsername(ctx context.Context, arg SetUsernameParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUsername, arg.ID, arg.Username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userByID = `-- name: UserByID :one
SELECT u.id, u.phone, u.first_name, u.last_name, u.created_at, u.is_online, u.last_seen_at,
       un.handle AS username
FROM users u
LEFT JOIN usernames un ON un.owner_type = 'user' AND un.owner_id = u.id
WHERE u.id = $1
`

type UserByIDRow struct {
	ID         int64
	Phone      string
	FirstName  string
	LastName   string
	CreatedAt  pgtype.Timestamptz
	IsOnline   bool
	LastSeenAt pgtype.Timestamptz
	Username   *string
}

func (q *Queries) UserByID(ctx context.Context, id int64) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.Username,
	)
	return i, err
}

const userByPhone = `-- name: UserByPhone :one
SELECT u.id, u.phone, u.first_name, u.last_name, u.created_at, u.is_online, u.last_seen_at,
       un.handle AS username
FROM users u
LEFT JOIN usernames un ON un.owner_type = 'user' AND un.owner_id = u.id
WHERE u.phone = $1
`

type UserByPhoneRow struct {
	ID         int64
	Phone      string
	FirstName  string
	LastName   string
	CreatedAt  pgtype.Timestamptz
	IsOnline   bool
	LastSeenAt pgtype.Timestamptz
	Username   *string
}

func (q *Queries) UserByPhone(ctx context.Context, phone string) (UserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, userByPhone, phone)
	var i UserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.Username,
	)
	return i, err
}
